/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap
 *  com.mojang.datafixers.DSL
 *  com.mojang.datafixers.DataFix
 *  com.mojang.datafixers.DataFixer
 *  com.mojang.datafixers.DataFixerBuilder
 *  com.mojang.datafixers.Typed
 *  com.mojang.datafixers.schemas.Schema
 */
package net.minecraft.datafixer;

import com.google.common.collect.ImmutableMap;
import com.mojang.datafixers.DSL;
import com.mojang.datafixers.DataFix;
import com.mojang.datafixers.DataFixer;
import com.mojang.datafixers.DataFixerBuilder;
import com.mojang.datafixers.Typed;
import com.mojang.datafixers.schemas.Schema;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiFunction;
import java.util.function.UnaryOperator;
import net.minecraft.SharedConstants;
import net.minecraft.datafixer.TypeReferences;
import net.minecraft.datafixer.fix.AddTrappedChestFix;
import net.minecraft.datafixer.fix.AdvancementRenameFix;
import net.minecraft.datafixer.fix.AdvancementsFix;
import net.minecraft.datafixer.fix.BedBlockEntityFix;
import net.minecraft.datafixer.fix.BedItemColorFix;
import net.minecraft.datafixer.fix.BeehiveRenameFix;
import net.minecraft.datafixer.fix.BiomeFormatFix;
import net.minecraft.datafixer.fix.BiomeRenameFix;
import net.minecraft.datafixer.fix.BiomesFix;
import net.minecraft.datafixer.fix.BitStorageAlignFix;
import net.minecraft.datafixer.fix.BlockEntityBannerColorFix;
import net.minecraft.datafixer.fix.BlockEntityBlockStateFix;
import net.minecraft.datafixer.fix.BlockEntityCustomNameToTextFix;
import net.minecraft.datafixer.fix.BlockEntityIdFix;
import net.minecraft.datafixer.fix.BlockEntityJukeboxFix;
import net.minecraft.datafixer.fix.BlockEntityKeepPacked;
import net.minecraft.datafixer.fix.BlockEntityShulkerBoxColorFix;
import net.minecraft.datafixer.fix.BlockEntitySignTextStrictJsonFix;
import net.minecraft.datafixer.fix.BlockEntityUuidFix;
import net.minecraft.datafixer.fix.BlockNameFix;
import net.minecraft.datafixer.fix.BlockNameFlatteningFix;
import net.minecraft.datafixer.fix.BlockStateStructureTemplateFix;
import net.minecraft.datafixer.fix.CatTypeFix;
import net.minecraft.datafixer.fix.ChoiceFix;
import net.minecraft.datafixer.fix.ChoiceTypesFix;
import net.minecraft.datafixer.fix.ChunkLightRemoveFix;
import net.minecraft.datafixer.fix.ChunkPalettedStorageFix;
import net.minecraft.datafixer.fix.ChunkStatusFix;
import net.minecraft.datafixer.fix.ChunkStatusFix2;
import net.minecraft.datafixer.fix.ChunkStructuresTemplateRenameFix;
import net.minecraft.datafixer.fix.ChunkToProtoChunkFix;
import net.minecraft.datafixer.fix.ColorlessShulkerEntityFix;
import net.minecraft.datafixer.fix.EntityArmorStandSilentFix;
import net.minecraft.datafixer.fix.EntityBlockStateFix;
import net.minecraft.datafixer.fix.EntityCatSplitFix;
import net.minecraft.datafixer.fix.EntityCodSalmonFix;
import net.minecraft.datafixer.fix.EntityCustomNameToTextFix;
import net.minecraft.datafixer.fix.EntityElderGuardianSplitFix;
import net.minecraft.datafixer.fix.EntityEquipmentToArmorAndHandFix;
import net.minecraft.datafixer.fix.EntityHealthFix;
import net.minecraft.datafixer.fix.EntityHorseSaddleFix;
import net.minecraft.datafixer.fix.EntityHorseSplitFix;
import net.minecraft.datafixer.fix.EntityIdFix;
import net.minecraft.datafixer.fix.EntityItemFrameDirectionFix;
import net.minecraft.datafixer.fix.EntityMinecartIdentifiersFix;
import net.minecraft.datafixer.fix.EntityPaintingMotiveFix;
import net.minecraft.datafixer.fix.EntityProjectileOwnerFix;
import net.minecraft.datafixer.fix.EntityPufferfishRenameFix;
import net.minecraft.datafixer.fix.EntityRavagerRenameFix;
import net.minecraft.datafixer.fix.EntityRedundantChanceTagsFix;
import net.minecraft.datafixer.fix.EntityRidingToPassengerFix;
import net.minecraft.datafixer.fix.EntityShulkerColorFix;
import net.minecraft.datafixer.fix.EntityShulkerRotationFix;
import net.minecraft.datafixer.fix.EntitySkeletonSplitFix;
import net.minecraft.datafixer.fix.EntityStringUuidFix;
import net.minecraft.datafixer.fix.EntityTheRenameningBlock;
import net.minecraft.datafixer.fix.EntityTippedArrowFix;
import net.minecraft.datafixer.fix.EntityUuidFix;
import net.minecraft.datafixer.fix.EntityWolfColorFix;
import net.minecraft.datafixer.fix.EntityZombieSplitFix;
import net.minecraft.datafixer.fix.EntityZombieVillagerTypeFix;
import net.minecraft.datafixer.fix.EntityZombifiedPiglinRenameFix;
import net.minecraft.datafixer.fix.FurnaceRecipesFix;
import net.minecraft.datafixer.fix.HangingEntityFix;
import net.minecraft.datafixer.fix.HeightmapRenamingFix;
import net.minecraft.datafixer.fix.IglooMetadataRemovalFix;
import net.minecraft.datafixer.fix.ItemBannerColorFix;
import net.minecraft.datafixer.fix.ItemCustomNameToComponentFix;
import net.minecraft.datafixer.fix.ItemIdFix;
import net.minecraft.datafixer.fix.ItemInstanceMapIdFix;
import net.minecraft.datafixer.fix.ItemInstanceSpawnEggFix;
import net.minecraft.datafixer.fix.ItemInstanceTheFlatteningFix;
import net.minecraft.datafixer.fix.ItemLoreToTextFix;
import net.minecraft.datafixer.fix.ItemNameFix;
import net.minecraft.datafixer.fix.ItemPotionFix;
import net.minecraft.datafixer.fix.ItemShulkerBoxColorFix;
import net.minecraft.datafixer.fix.ItemSpawnEggFix;
import net.minecraft.datafixer.fix.ItemStackEnchantmentFix;
import net.minecraft.datafixer.fix.ItemStackUuidFix;
import net.minecraft.datafixer.fix.ItemWaterPotionFix;
import net.minecraft.datafixer.fix.ItemWrittenBookPagesStrictJsonFix;
import net.minecraft.datafixer.fix.JigsawPropertiesFix;
import net.minecraft.datafixer.fix.JigsawRotationFix;
import net.minecraft.datafixer.fix.LeavesFix;
import net.minecraft.datafixer.fix.LevelDataGeneratorOptionsFix;
import net.minecraft.datafixer.fix.LevelFlatGeneratorInfoFix;
import net.minecraft.datafixer.fix.MapIdFix;
import net.minecraft.datafixer.fix.MemoryExpiryDataFix;
import net.minecraft.datafixer.fix.MissingDimensionFix;
import net.minecraft.datafixer.fix.MobSpawnerEntityIdentifiersFix;
import net.minecraft.datafixer.fix.NewVillageFix;
import net.minecraft.datafixer.fix.ObjectiveDisplayNameFix;
import net.minecraft.datafixer.fix.ObjectiveRenderTypeFix;
import net.minecraft.datafixer.fix.OminousBannerBlockEntityRenameFix;
import net.minecraft.datafixer.fix.OminousBannerItemRenameFix;
import net.minecraft.datafixer.fix.OptionFix;
import net.minecraft.datafixer.fix.OptionsAddTextBackgroundFix;
import net.minecraft.datafixer.fix.OptionsForceVBOFix;
import net.minecraft.datafixer.fix.OptionsKeyLwjgl3Fix;
import net.minecraft.datafixer.fix.OptionsKeyTranslationFix;
import net.minecraft.datafixer.fix.OptionsLowerCaseLanguageFix;
import net.minecraft.datafixer.fix.PersistentStateUuidFix;
import net.minecraft.datafixer.fix.PlayerUuidFix;
import net.minecraft.datafixer.fix.PointOfInterestReorganizationFix;
import net.minecraft.datafixer.fix.RecipeFix;
import net.minecraft.datafixer.fix.RecipeRenameFix;
import net.minecraft.datafixer.fix.RecipeRenamingFix;
import net.minecraft.datafixer.fix.RedstoneConnectionsFix;
import net.minecraft.datafixer.fix.RemoveGolemGossipFix;
import net.minecraft.datafixer.fix.RemovePoiValidTagFix;
import net.minecraft.datafixer.fix.RenameItemStackAttributesFix;
import net.minecraft.datafixer.fix.SavedDataVillageCropFix;
import net.minecraft.datafixer.fix.StatsCounterFix;
import net.minecraft.datafixer.fix.StriderGravityFix;
import net.minecraft.datafixer.fix.StructureReferenceFix;
import net.minecraft.datafixer.fix.StructureSeparationDataFix;
import net.minecraft.datafixer.fix.SwimStatsRenameFix;
import net.minecraft.datafixer.fix.TeamDisplayNameFix;
import net.minecraft.datafixer.fix.VillagerFollowRangeFix;
import net.minecraft.datafixer.fix.VillagerGossipFix;
import net.minecraft.datafixer.fix.VillagerProfessionFix;
import net.minecraft.datafixer.fix.VillagerTradeFix;
import net.minecraft.datafixer.fix.VillagerXpRebuildFix;
import net.minecraft.datafixer.fix.WallPropertyFix;
import net.minecraft.datafixer.fix.WorldUuidFix;
import net.minecraft.datafixer.fix.WriteAndReadFix;
import net.minecraft.datafixer.fix.ZombieVillagerXpRebuildFix;
import net.minecraft.datafixer.mapping.LegacyCoralBlockMapping;
import net.minecraft.datafixer.mapping.LegacyCoralFanBlockMapping;
import net.minecraft.datafixer.mapping.LegacyDyeItemMapping;
import net.minecraft.datafixer.schema.IdentifierNormalizingSchema;
import net.minecraft.datafixer.schema.Schema100;
import net.minecraft.datafixer.schema.Schema102;
import net.minecraft.datafixer.schema.Schema1022;
import net.minecraft.datafixer.schema.Schema106;
import net.minecraft.datafixer.schema.Schema107;
import net.minecraft.datafixer.schema.Schema1125;
import net.minecraft.datafixer.schema.Schema135;
import net.minecraft.datafixer.schema.Schema143;
import net.minecraft.datafixer.schema.Schema1451;
import net.minecraft.datafixer.schema.Schema1451v1;
import net.minecraft.datafixer.schema.Schema1451v2;
import net.minecraft.datafixer.schema.Schema1451v3;
import net.minecraft.datafixer.schema.Schema1451v4;
import net.minecraft.datafixer.schema.Schema1451v5;
import net.minecraft.datafixer.schema.Schema1451v6;
import net.minecraft.datafixer.schema.Schema1451v7;
import net.minecraft.datafixer.schema.Schema1460;
import net.minecraft.datafixer.schema.Schema1466;
import net.minecraft.datafixer.schema.Schema1470;
import net.minecraft.datafixer.schema.Schema1481;
import net.minecraft.datafixer.schema.Schema1483;
import net.minecraft.datafixer.schema.Schema1486;
import net.minecraft.datafixer.schema.Schema1510;
import net.minecraft.datafixer.schema.Schema1800;
import net.minecraft.datafixer.schema.Schema1801;
import net.minecraft.datafixer.schema.Schema1904;
import net.minecraft.datafixer.schema.Schema1906;
import net.minecraft.datafixer.schema.Schema1909;
import net.minecraft.datafixer.schema.Schema1920;
import net.minecraft.datafixer.schema.Schema1928;
import net.minecraft.datafixer.schema.Schema1929;
import net.minecraft.datafixer.schema.Schema1931;
import net.minecraft.datafixer.schema.Schema2100;
import net.minecraft.datafixer.schema.Schema2501;
import net.minecraft.datafixer.schema.Schema2502;
import net.minecraft.datafixer.schema.Schema2505;
import net.minecraft.datafixer.schema.Schema2509;
import net.minecraft.datafixer.schema.Schema2519;
import net.minecraft.datafixer.schema.Schema2522;
import net.minecraft.datafixer.schema.Schema2551;
import net.minecraft.datafixer.schema.Schema2568;
import net.minecraft.datafixer.schema.Schema501;
import net.minecraft.datafixer.schema.Schema700;
import net.minecraft.datafixer.schema.Schema701;
import net.minecraft.datafixer.schema.Schema702;
import net.minecraft.datafixer.schema.Schema703;
import net.minecraft.datafixer.schema.Schema704;
import net.minecraft.datafixer.schema.Schema705;
import net.minecraft.datafixer.schema.Schema808;
import net.minecraft.datafixer.schema.Schema99;
import net.minecraft.util.Util;

public class Schemas {
    private static final BiFunction<Integer, Schema, Schema> EMPTY = Schema::new;
    private static final BiFunction<Integer, Schema, Schema> EMPTY_IDENTIFIER_NORMALIZE = IdentifierNormalizingSchema::new;
    private static final DataFixer FIXER = Schemas.create();

    private static DataFixer create() {
        DataFixerBuilder dataFixerBuilder = new DataFixerBuilder(SharedConstants.getGameVersion().getWorldVersion());
        Schemas.build(dataFixerBuilder);
        return dataFixerBuilder.build(Util.getBootstrapExecutor());
    }

    public static DataFixer getFixer() {
        return FIXER;
    }

    private static void build(DataFixerBuilder builder) {
        Schema schema = builder.addSchema(99, Schema99::new);
        _snowman = builder.addSchema(100, Schema100::new);
        builder.addFixer((DataFix)new EntityEquipmentToArmorAndHandFix(_snowman, true));
        _snowman = builder.addSchema(101, EMPTY);
        builder.addFixer((DataFix)new BlockEntitySignTextStrictJsonFix(_snowman, false));
        _snowman = builder.addSchema(102, Schema102::new);
        builder.addFixer((DataFix)new ItemIdFix(_snowman, true));
        builder.addFixer((DataFix)new ItemPotionFix(_snowman, false));
        _snowman = builder.addSchema(105, EMPTY);
        builder.addFixer((DataFix)new ItemSpawnEggFix(_snowman, true));
        _snowman = builder.addSchema(106, Schema106::new);
        builder.addFixer((DataFix)new MobSpawnerEntityIdentifiersFix(_snowman, true));
        _snowman = builder.addSchema(107, Schema107::new);
        builder.addFixer((DataFix)new EntityMinecartIdentifiersFix(_snowman, true));
        _snowman = builder.addSchema(108, EMPTY);
        builder.addFixer((DataFix)new EntityStringUuidFix(_snowman, true));
        _snowman = builder.addSchema(109, EMPTY);
        builder.addFixer((DataFix)new EntityHealthFix(_snowman, true));
        _snowman = builder.addSchema(110, EMPTY);
        builder.addFixer((DataFix)new EntityHorseSaddleFix(_snowman, true));
        _snowman = builder.addSchema(111, EMPTY);
        builder.addFixer((DataFix)new HangingEntityFix(_snowman, true));
        _snowman = builder.addSchema(113, EMPTY);
        builder.addFixer((DataFix)new EntityRedundantChanceTagsFix(_snowman, true));
        _snowman = builder.addSchema(135, Schema135::new);
        builder.addFixer((DataFix)new EntityRidingToPassengerFix(_snowman, true));
        _snowman = builder.addSchema(143, Schema143::new);
        builder.addFixer((DataFix)new EntityTippedArrowFix(_snowman, true));
        _snowman = builder.addSchema(147, EMPTY);
        builder.addFixer((DataFix)new EntityArmorStandSilentFix(_snowman, true));
        _snowman = builder.addSchema(165, EMPTY);
        builder.addFixer((DataFix)new ItemWrittenBookPagesStrictJsonFix(_snowman, true));
        _snowman = builder.addSchema(501, Schema501::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Add 1.10 entities fix", TypeReferences.ENTITY));
        _snowman = builder.addSchema(502, EMPTY);
        builder.addFixer(ItemNameFix.create(_snowman, "cooked_fished item renamer", string -> Objects.equals(IdentifierNormalizingSchema.normalize(string), "minecraft:cooked_fished") ? "minecraft:cooked_fish" : string));
        builder.addFixer((DataFix)new EntityZombieVillagerTypeFix(_snowman, false));
        _snowman = builder.addSchema(505, EMPTY);
        builder.addFixer((DataFix)new OptionsForceVBOFix(_snowman, false));
        _snowman = builder.addSchema(700, Schema700::new);
        builder.addFixer((DataFix)new EntityElderGuardianSplitFix(_snowman, true));
        _snowman = builder.addSchema(701, Schema701::new);
        builder.addFixer((DataFix)new EntitySkeletonSplitFix(_snowman, true));
        _snowman = builder.addSchema(702, Schema702::new);
        builder.addFixer((DataFix)new EntityZombieSplitFix(_snowman, true));
        _snowman = builder.addSchema(703, Schema703::new);
        builder.addFixer((DataFix)new EntityHorseSplitFix(_snowman, true));
        _snowman = builder.addSchema(704, Schema704::new);
        builder.addFixer((DataFix)new BlockEntityIdFix(_snowman, true));
        _snowman = builder.addSchema(705, Schema705::new);
        builder.addFixer((DataFix)new EntityIdFix(_snowman, true));
        _snowman = builder.addSchema(804, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new ItemBannerColorFix(_snowman, true));
        _snowman = builder.addSchema(806, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new ItemWaterPotionFix(_snowman, false));
        _snowman = builder.addSchema(808, Schema808::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "added shulker box", TypeReferences.BLOCK_ENTITY));
        _snowman = builder.addSchema(808, 1, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new EntityShulkerColorFix(_snowman, false));
        _snowman = builder.addSchema(813, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new ItemShulkerBoxColorFix(_snowman, false));
        builder.addFixer((DataFix)new BlockEntityShulkerBoxColorFix(_snowman, false));
        _snowman = builder.addSchema(816, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new OptionsLowerCaseLanguageFix(_snowman, false));
        _snowman = builder.addSchema(820, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer(ItemNameFix.create(_snowman, "totem item renamer", Schemas.method_30068("minecraft:totem", "minecraft:totem_of_undying")));
        _snowman = builder.addSchema(1022, Schema1022::new);
        builder.addFixer((DataFix)new WriteAndReadFix(_snowman, "added shoulder entities to players", TypeReferences.PLAYER));
        _snowman = builder.addSchema(1125, Schema1125::new);
        builder.addFixer((DataFix)new BedBlockEntityFix(_snowman, true));
        builder.addFixer((DataFix)new BedItemColorFix(_snowman, false));
        _snowman = builder.addSchema(1344, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new OptionsKeyLwjgl3Fix(_snowman, false));
        _snowman = builder.addSchema(1446, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new OptionsKeyTranslationFix(_snowman, false));
        _snowman = builder.addSchema(1450, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new BlockStateStructureTemplateFix(_snowman, false));
        _snowman = builder.addSchema(1451, Schema1451::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "AddTrappedChestFix", TypeReferences.BLOCK_ENTITY));
        _snowman = builder.addSchema(1451, 1, Schema1451v1::new);
        builder.addFixer((DataFix)new ChunkPalettedStorageFix(_snowman, true));
        _snowman = builder.addSchema(1451, 2, Schema1451v2::new);
        builder.addFixer((DataFix)new BlockEntityBlockStateFix(_snowman, true));
        _snowman = builder.addSchema(1451, 3, Schema1451v3::new);
        builder.addFixer((DataFix)new EntityBlockStateFix(_snowman, true));
        builder.addFixer((DataFix)new ItemInstanceMapIdFix(_snowman, false));
        _snowman = builder.addSchema(1451, 4, Schema1451v4::new);
        builder.addFixer((DataFix)new BlockNameFlatteningFix(_snowman, true));
        builder.addFixer((DataFix)new ItemInstanceTheFlatteningFix(_snowman, false));
        _snowman = builder.addSchema(1451, 5, Schema1451v5::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "RemoveNoteBlockFlowerPotFix", TypeReferences.BLOCK_ENTITY));
        builder.addFixer((DataFix)new ItemInstanceSpawnEggFix(_snowman, false));
        builder.addFixer((DataFix)new EntityWolfColorFix(_snowman, false));
        builder.addFixer((DataFix)new BlockEntityBannerColorFix(_snowman, false));
        builder.addFixer((DataFix)new LevelFlatGeneratorInfoFix(_snowman, false));
        _snowman = builder.addSchema(1451, 6, Schema1451v6::new);
        builder.addFixer((DataFix)new StatsCounterFix(_snowman, true));
        builder.addFixer((DataFix)new BlockEntityJukeboxFix(_snowman, false));
        _snowman = builder.addSchema(1451, 7, Schema1451v7::new);
        builder.addFixer((DataFix)new SavedDataVillageCropFix(_snowman, true));
        _snowman = builder.addSchema(1451, 7, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new VillagerTradeFix(_snowman, false));
        _snowman = builder.addSchema(1456, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new EntityItemFrameDirectionFix(_snowman, false));
        _snowman = builder.addSchema(1458, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new EntityCustomNameToTextFix(_snowman, false));
        builder.addFixer((DataFix)new ItemCustomNameToComponentFix(_snowman, false));
        builder.addFixer((DataFix)new BlockEntityCustomNameToTextFix(_snowman, false));
        _snowman = builder.addSchema(1460, Schema1460::new);
        builder.addFixer((DataFix)new EntityPaintingMotiveFix(_snowman, false));
        _snowman = builder.addSchema(1466, Schema1466::new);
        builder.addFixer((DataFix)new ChunkToProtoChunkFix(_snowman, true));
        _snowman = builder.addSchema(1470, Schema1470::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Add 1.13 entities fix", TypeReferences.ENTITY));
        _snowman = builder.addSchema(1474, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new ColorlessShulkerEntityFix(_snowman, false));
        builder.addFixer(BlockNameFix.create(_snowman, "Colorless shulker block fixer", string -> Objects.equals(IdentifierNormalizingSchema.normalize(string), "minecraft:purple_shulker_box") ? "minecraft:shulker_box" : string));
        builder.addFixer(ItemNameFix.create(_snowman, "Colorless shulker item fixer", string -> Objects.equals(IdentifierNormalizingSchema.normalize(string), "minecraft:purple_shulker_box") ? "minecraft:shulker_box" : string));
        _snowman = builder.addSchema(1475, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer(BlockNameFix.create(_snowman, "Flowing fixer", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:flowing_water", (Object)"minecraft:water", (Object)"minecraft:flowing_lava", (Object)"minecraft:lava"))));
        _snowman = builder.addSchema(1480, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer(BlockNameFix.create(_snowman, "Rename coral blocks", Schemas.method_30070(LegacyCoralBlockMapping.MAP)));
        builder.addFixer(ItemNameFix.create(_snowman, "Rename coral items", Schemas.method_30070(LegacyCoralBlockMapping.MAP)));
        _snowman = builder.addSchema(1481, Schema1481::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Add conduit", TypeReferences.BLOCK_ENTITY));
        _snowman = builder.addSchema(1483, Schema1483::new);
        builder.addFixer((DataFix)new EntityPufferfishRenameFix(_snowman, true));
        builder.addFixer(ItemNameFix.create(_snowman, "Rename pufferfish egg item", Schemas.method_30070(EntityPufferfishRenameFix.RENAMED_FISH)));
        _snowman = builder.addSchema(1484, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer(ItemNameFix.create(_snowman, "Rename seagrass items", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:sea_grass", (Object)"minecraft:seagrass", (Object)"minecraft:tall_sea_grass", (Object)"minecraft:tall_seagrass"))));
        builder.addFixer(BlockNameFix.create(_snowman, "Rename seagrass blocks", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:sea_grass", (Object)"minecraft:seagrass", (Object)"minecraft:tall_sea_grass", (Object)"minecraft:tall_seagrass"))));
        builder.addFixer((DataFix)new HeightmapRenamingFix(_snowman, false));
        _snowman = builder.addSchema(1486, Schema1486::new);
        builder.addFixer((DataFix)new EntityCodSalmonFix(_snowman, true));
        builder.addFixer(ItemNameFix.create(_snowman, "Rename cod/salmon egg items", Schemas.method_30070(EntityCodSalmonFix.SPAWN_EGGS)));
        _snowman = builder.addSchema(1487, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer(ItemNameFix.create(_snowman, "Rename prismarine_brick(s)_* blocks", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:prismarine_bricks_slab", (Object)"minecraft:prismarine_brick_slab", (Object)"minecraft:prismarine_bricks_stairs", (Object)"minecraft:prismarine_brick_stairs"))));
        builder.addFixer(BlockNameFix.create(_snowman, "Rename prismarine_brick(s)_* items", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:prismarine_bricks_slab", (Object)"minecraft:prismarine_brick_slab", (Object)"minecraft:prismarine_bricks_stairs", (Object)"minecraft:prismarine_brick_stairs"))));
        _snowman = builder.addSchema(1488, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer(BlockNameFix.create(_snowman, "Rename kelp/kelptop", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:kelp_top", (Object)"minecraft:kelp", (Object)"minecraft:kelp", (Object)"minecraft:kelp_plant"))));
        builder.addFixer(ItemNameFix.create(_snowman, "Rename kelptop", Schemas.method_30068("minecraft:kelp_top", "minecraft:kelp")));
        builder.addFixer((DataFix)new ChoiceFix(_snowman, false, "Command block block entity custom name fix", TypeReferences.BLOCK_ENTITY, "minecraft:command_block"){

            protected Typed<?> transform(Typed<?> inputType) {
                return inputType.update(DSL.remainderFinder(), EntityCustomNameToTextFix::fixCustomName);
            }
        });
        builder.addFixer((DataFix)new ChoiceFix(_snowman, false, "Command block minecart custom name fix", TypeReferences.ENTITY, "minecraft:commandblock_minecart"){

            protected Typed<?> transform(Typed<?> inputType) {
                return inputType.update(DSL.remainderFinder(), EntityCustomNameToTextFix::fixCustomName);
            }
        });
        builder.addFixer((DataFix)new IglooMetadataRemovalFix(_snowman, false));
        _snowman = builder.addSchema(1490, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer(BlockNameFix.create(_snowman, "Rename melon_block", Schemas.method_30068("minecraft:melon_block", "minecraft:melon")));
        builder.addFixer(ItemNameFix.create(_snowman, "Rename melon_block/melon/speckled_melon", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:melon_block", (Object)"minecraft:melon", (Object)"minecraft:melon", (Object)"minecraft:melon_slice", (Object)"minecraft:speckled_melon", (Object)"minecraft:glistering_melon_slice"))));
        _snowman = builder.addSchema(1492, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new ChunkStructuresTemplateRenameFix(_snowman, false));
        _snowman = builder.addSchema(1494, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new ItemStackEnchantmentFix(_snowman, false));
        _snowman = builder.addSchema(1496, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new LeavesFix(_snowman, false));
        _snowman = builder.addSchema(1500, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new BlockEntityKeepPacked(_snowman, false));
        _snowman = builder.addSchema(1501, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new AdvancementsFix(_snowman, false));
        _snowman = builder.addSchema(1502, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new RecipeFix(_snowman, false));
        _snowman = builder.addSchema(1506, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new LevelDataGeneratorOptionsFix(_snowman, false));
        _snowman = builder.addSchema(1510, Schema1510::new);
        builder.addFixer(BlockNameFix.create(_snowman, "Block renamening fix", Schemas.method_30070(EntityTheRenameningBlock.BLOCKS)));
        builder.addFixer(ItemNameFix.create(_snowman, "Item renamening fix", Schemas.method_30070(EntityTheRenameningBlock.ITEMS)));
        builder.addFixer((DataFix)new RecipeRenamingFix(_snowman, false));
        builder.addFixer((DataFix)new EntityTheRenameningBlock(_snowman, true));
        builder.addFixer((DataFix)new SwimStatsRenameFix(_snowman, false));
        _snowman = builder.addSchema(1514, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new ObjectiveDisplayNameFix(_snowman, false));
        builder.addFixer((DataFix)new TeamDisplayNameFix(_snowman, false));
        builder.addFixer((DataFix)new ObjectiveRenderTypeFix(_snowman, false));
        _snowman = builder.addSchema(1515, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer(BlockNameFix.create(_snowman, "Rename coral fan blocks", Schemas.method_30070(LegacyCoralFanBlockMapping.MAP)));
        _snowman = builder.addSchema(1624, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new AddTrappedChestFix(_snowman, false));
        _snowman = builder.addSchema(1800, Schema1800::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Added 1.14 mobs fix", TypeReferences.ENTITY));
        builder.addFixer(ItemNameFix.create(_snowman, "Rename dye items", Schemas.method_30070(LegacyDyeItemMapping.MAP)));
        _snowman = builder.addSchema(1801, Schema1801::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Added Illager Beast", TypeReferences.ENTITY));
        _snowman = builder.addSchema(1802, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer(BlockNameFix.create(_snowman, "Rename sign blocks & stone slabs", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:stone_slab", (Object)"minecraft:smooth_stone_slab", (Object)"minecraft:sign", (Object)"minecraft:oak_sign", (Object)"minecraft:wall_sign", (Object)"minecraft:oak_wall_sign"))));
        builder.addFixer(ItemNameFix.create(_snowman, "Rename sign item & stone slabs", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:stone_slab", (Object)"minecraft:smooth_stone_slab", (Object)"minecraft:sign", (Object)"minecraft:oak_sign"))));
        _snowman = builder.addSchema(1803, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new ItemLoreToTextFix(_snowman, false));
        _snowman = builder.addSchema(1904, Schema1904::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Added Cats", TypeReferences.ENTITY));
        builder.addFixer((DataFix)new EntityCatSplitFix(_snowman, false));
        _snowman = builder.addSchema(1905, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new ChunkStatusFix(_snowman, false));
        _snowman = builder.addSchema(1906, Schema1906::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Add POI Blocks", TypeReferences.BLOCK_ENTITY));
        _snowman = builder.addSchema(1909, Schema1909::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Add jigsaw", TypeReferences.BLOCK_ENTITY));
        _snowman = builder.addSchema(1911, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new ChunkStatusFix2(_snowman, false));
        _snowman = builder.addSchema(1917, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new CatTypeFix(_snowman, false));
        _snowman = builder.addSchema(1918, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new VillagerProfessionFix(_snowman, "minecraft:villager"));
        builder.addFixer((DataFix)new VillagerProfessionFix(_snowman, "minecraft:zombie_villager"));
        _snowman = builder.addSchema(1920, Schema1920::new);
        builder.addFixer((DataFix)new NewVillageFix(_snowman, false));
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Add campfire", TypeReferences.BLOCK_ENTITY));
        _snowman = builder.addSchema(1925, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new MapIdFix(_snowman, false));
        _snowman = builder.addSchema(1928, Schema1928::new);
        builder.addFixer((DataFix)new EntityRavagerRenameFix(_snowman, true));
        builder.addFixer(ItemNameFix.create(_snowman, "Rename ravager egg item", Schemas.method_30070(EntityRavagerRenameFix.ITEMS)));
        _snowman = builder.addSchema(1929, Schema1929::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Add Wandering Trader and Trader Llama", TypeReferences.ENTITY));
        _snowman = builder.addSchema(1931, Schema1931::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Added Fox", TypeReferences.ENTITY));
        _snowman = builder.addSchema(1936, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new OptionsAddTextBackgroundFix(_snowman, false));
        _snowman = builder.addSchema(1946, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new PointOfInterestReorganizationFix(_snowman, false));
        _snowman = builder.addSchema(1948, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new OminousBannerItemRenameFix(_snowman, false));
        _snowman = builder.addSchema(1953, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new OminousBannerBlockEntityRenameFix(_snowman, false));
        _snowman = builder.addSchema(1955, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new VillagerXpRebuildFix(_snowman, false));
        builder.addFixer((DataFix)new ZombieVillagerXpRebuildFix(_snowman, false));
        _snowman = builder.addSchema(1961, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new ChunkLightRemoveFix(_snowman, false));
        _snowman = builder.addSchema(1963, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new RemoveGolemGossipFix(_snowman, false));
        _snowman = builder.addSchema(2100, Schema2100::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Added Bee and Bee Stinger", TypeReferences.ENTITY));
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Add beehive", TypeReferences.BLOCK_ENTITY));
        builder.addFixer((DataFix)new RecipeRenameFix(_snowman, false, "Rename sugar recipe", Schemas.method_30068("minecraft:sugar", "sugar_from_sugar_cane")));
        builder.addFixer((DataFix)new AdvancementRenameFix(_snowman, false, "Rename sugar recipe advancement", Schemas.method_30068("minecraft:recipes/misc/sugar", "minecraft:recipes/misc/sugar_from_sugar_cane")));
        _snowman = builder.addSchema(2202, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new BiomeFormatFix(_snowman, false));
        _snowman = builder.addSchema(2209, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer(ItemNameFix.create(_snowman, "Rename bee_hive item to beehive", Schemas.method_30068("minecraft:bee_hive", "minecraft:beehive")));
        builder.addFixer((DataFix)new BeehiveRenameFix(_snowman));
        builder.addFixer(BlockNameFix.create(_snowman, "Rename bee_hive block to beehive", Schemas.method_30068("minecraft:bee_hive", "minecraft:beehive")));
        _snowman = builder.addSchema(2211, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new StructureReferenceFix(_snowman, false));
        _snowman = builder.addSchema(2218, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new RemovePoiValidTagFix(_snowman, false));
        _snowman = builder.addSchema(2501, Schema2501::new);
        builder.addFixer((DataFix)new FurnaceRecipesFix(_snowman, true));
        _snowman = builder.addSchema(2502, Schema2502::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Added Hoglin", TypeReferences.ENTITY));
        _snowman = builder.addSchema(2503, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new WallPropertyFix(_snowman, false));
        builder.addFixer((DataFix)new AdvancementRenameFix(_snowman, false, "Composter category change", Schemas.method_30068("minecraft:recipes/misc/composter", "minecraft:recipes/decorations/composter")));
        _snowman = builder.addSchema(2505, Schema2505::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Added Piglin", TypeReferences.ENTITY));
        builder.addFixer((DataFix)new MemoryExpiryDataFix(_snowman, "minecraft:villager"));
        _snowman = builder.addSchema(2508, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer(ItemNameFix.create(_snowman, "Renamed fungi items to fungus", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:warped_fungi", (Object)"minecraft:warped_fungus", (Object)"minecraft:crimson_fungi", (Object)"minecraft:crimson_fungus"))));
        builder.addFixer(BlockNameFix.create(_snowman, "Renamed fungi blocks to fungus", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:warped_fungi", (Object)"minecraft:warped_fungus", (Object)"minecraft:crimson_fungi", (Object)"minecraft:crimson_fungus"))));
        _snowman = builder.addSchema(2509, Schema2509::new);
        builder.addFixer((DataFix)new EntityZombifiedPiglinRenameFix(_snowman));
        builder.addFixer(ItemNameFix.create(_snowman, "Rename zombie pigman egg item", Schemas.method_30070(EntityZombifiedPiglinRenameFix.RENAMES)));
        _snowman = builder.addSchema(2511, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new EntityProjectileOwnerFix(_snowman));
        _snowman = builder.addSchema(2514, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new EntityUuidFix(_snowman));
        builder.addFixer((DataFix)new BlockEntityUuidFix(_snowman));
        builder.addFixer((DataFix)new PlayerUuidFix(_snowman));
        builder.addFixer((DataFix)new WorldUuidFix(_snowman));
        builder.addFixer((DataFix)new PersistentStateUuidFix(_snowman));
        builder.addFixer((DataFix)new ItemStackUuidFix(_snowman));
        _snowman = builder.addSchema(2516, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new VillagerGossipFix(_snowman, "minecraft:villager"));
        builder.addFixer((DataFix)new VillagerGossipFix(_snowman, "minecraft:zombie_villager"));
        _snowman = builder.addSchema(2518, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new JigsawPropertiesFix(_snowman, false));
        builder.addFixer((DataFix)new JigsawRotationFix(_snowman, false));
        _snowman = builder.addSchema(2519, Schema2519::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Added Strider", TypeReferences.ENTITY));
        _snowman = builder.addSchema(2522, Schema2522::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Added Zoglin", TypeReferences.ENTITY));
        _snowman = builder.addSchema(2523, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new RenameItemStackAttributesFix(_snowman));
        _snowman = builder.addSchema(2527, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new BitStorageAlignFix(_snowman));
        _snowman = builder.addSchema(2528, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer(ItemNameFix.create(_snowman, "Rename soul fire torch and soul fire lantern", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:soul_fire_torch", (Object)"minecraft:soul_torch", (Object)"minecraft:soul_fire_lantern", (Object)"minecraft:soul_lantern"))));
        builder.addFixer(BlockNameFix.create(_snowman, "Rename soul fire torch and soul fire lantern", Schemas.method_30070((Map<String, String>)ImmutableMap.of((Object)"minecraft:soul_fire_torch", (Object)"minecraft:soul_torch", (Object)"minecraft:soul_fire_wall_torch", (Object)"minecraft:soul_wall_torch", (Object)"minecraft:soul_fire_lantern", (Object)"minecraft:soul_lantern"))));
        _snowman = builder.addSchema(2529, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new StriderGravityFix(_snowman, false));
        _snowman = builder.addSchema(2531, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new RedstoneConnectionsFix(_snowman));
        _snowman = builder.addSchema(2533, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new VillagerFollowRangeFix(_snowman));
        _snowman = builder.addSchema(2535, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new EntityShulkerRotationFix(_snowman));
        _snowman = builder.addSchema(2550, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new StructureSeparationDataFix(_snowman));
        _snowman = builder.addSchema(2551, Schema2551::new);
        builder.addFixer((DataFix)new WriteAndReadFix(_snowman, "add types to WorldGenData", TypeReferences.CHUNK_GENERATOR_SETTINGS));
        _snowman = builder.addSchema(2552, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new BiomeRenameFix(_snowman, false, "Nether biome rename", (Map<String, String>)ImmutableMap.of((Object)"minecraft:nether", (Object)"minecraft:nether_wastes")));
        _snowman = builder.addSchema(2553, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new BiomesFix(_snowman, false));
        _snowman = builder.addSchema(2558, EMPTY_IDENTIFIER_NORMALIZE);
        builder.addFixer((DataFix)new MissingDimensionFix(_snowman, false));
        builder.addFixer((DataFix)new OptionFix(_snowman, false, "Rename swapHands setting", "key_key.swapHands", "key_key.swapOffhand"));
        _snowman = builder.addSchema(2568, Schema2568::new);
        builder.addFixer((DataFix)new ChoiceTypesFix(_snowman, "Added Piglin Brute", TypeReferences.ENTITY));
    }

    private static UnaryOperator<String> method_30070(Map<String, String> map) {
        return string -> map.getOrDefault(string, (String)string);
    }

    private static UnaryOperator<String> method_30068(String string, String string2) {
        return string3 -> Objects.equals(string3, string) ? string2 : string3;
    }
}

