import com.google.common.collect.UnmodifiableIterator;
import java.util.function.ToIntFunction;

public class bup {
   public static final buo a = a("air", new btr(ceg.c.a(cva.a).a().f().g()));
   public static final buo b = a("stone", new buo(ceg.c.a(cva.I, cvb.m).h().a(1.5F, 6.0F)));
   public static final buo c = a("granite", new buo(ceg.c.a(cva.I, cvb.l).h().a(1.5F, 6.0F)));
   public static final buo d = a("polished_granite", new buo(ceg.c.a(cva.I, cvb.l).h().a(1.5F, 6.0F)));
   public static final buo e = a("diorite", new buo(ceg.c.a(cva.I, cvb.p).h().a(1.5F, 6.0F)));
   public static final buo f = a("polished_diorite", new buo(ceg.c.a(cva.I, cvb.p).h().a(1.5F, 6.0F)));
   public static final buo g = a("andesite", new buo(ceg.c.a(cva.I, cvb.m).h().a(1.5F, 6.0F)));
   public static final buo h = a("polished_andesite", new buo(ceg.c.a(cva.I, cvb.m).h().a(1.5F, 6.0F)));
   public static final buo i = a("grass_block", new bxb(ceg.c.a(cva.t).d().d(0.6F).a(cae.c)));
   public static final buo j = a("dirt", new buo(ceg.c.a(cva.s, cvb.l).d(0.5F).a(cae.b)));
   public static final buo k = a("coarse_dirt", new buo(ceg.c.a(cva.s, cvb.l).d(0.5F).a(cae.b)));
   public static final buo l = a("podzol", new cab(ceg.c.a(cva.s, cvb.J).d(0.5F).a(cae.b)));
   public static final buo m = a("cobblestone", new buo(ceg.c.a(cva.I).h().a(2.0F, 6.0F)));
   public static final buo n = a("oak_planks", new buo(ceg.c.a(cva.y, cvb.o).a(2.0F, 3.0F).a(cae.a)));
   public static final buo o = a("spruce_planks", new buo(ceg.c.a(cva.y, cvb.J).a(2.0F, 3.0F).a(cae.a)));
   public static final buo p = a("birch_planks", new buo(ceg.c.a(cva.y, cvb.d).a(2.0F, 3.0F).a(cae.a)));
   public static final buo q = a("jungle_planks", new buo(ceg.c.a(cva.y, cvb.l).a(2.0F, 3.0F).a(cae.a)));
   public static final buo r = a("acacia_planks", new buo(ceg.c.a(cva.y, cvb.q).a(2.0F, 3.0F).a(cae.a)));
   public static final buo s = a("dark_oak_planks", new buo(ceg.c.a(cva.y, cvb.B).a(2.0F, 3.0F).a(cae.a)));
   public static final buo t = a("oak_sapling", new bzo(new cdv(), ceg.c.a(cva.e).a().d().c().a(cae.c)));
   public static final buo u = a("spruce_sapling", new bzo(new cdw(), ceg.c.a(cva.e).a().d().c().a(cae.c)));
   public static final buo v = a("birch_sapling", new bzo(new cds(), ceg.c.a(cva.e).a().d().c().a(cae.c)));
   public static final buo w = a("jungle_sapling", new bzo(new cdu(), ceg.c.a(cva.e).a().d().c().a(cae.c)));
   public static final buo x = a("acacia_sapling", new bzo(new cdr(), ceg.c.a(cva.e).a().d().c().a(cae.c)));
   public static final buo y = a("dark_oak_sapling", new bzo(new cdt(), ceg.c.a(cva.e).a().d().c().a(cae.c)));
   public static final buo z = a("bedrock", new buo(ceg.c.a(cva.I).a(-1.0F, 3600000.0F).f().a(bup::a)));
   public static final buo A = a("water", new byb(cuy.c, ceg.c.a(cva.j).a().d(100.0F).f()));
   public static final buo B = a("lava", new byb(cuy.e, ceg.c.a(cva.l).a().d().d(100.0F).a(var0 -> 15).f()));
   public static final buo C = a("sand", new bzn(14406560, ceg.c.a(cva.v, cvb.d).d(0.5F).a(cae.i)));
   public static final buo D = a("red_sand", new bzn(11098145, ceg.c.a(cva.v, cvb.q).d(0.5F).a(cae.i)));
   public static final buo E = a("gravel", new bxd(ceg.c.a(cva.v, cvb.m).d(0.6F).a(cae.b)));
   public static final buo F = a("gold_ore", new byr(ceg.c.a(cva.I).h().a(3.0F, 3.0F)));
   public static final buo G = a("iron_ore", new byr(ceg.c.a(cva.I).h().a(3.0F, 3.0F)));
   public static final buo H = a("coal_ore", new byr(ceg.c.a(cva.I).h().a(3.0F, 3.0F)));
   public static final buo I = a("nether_gold_ore", new byr(ceg.c.a(cva.I, cvb.K).h().a(3.0F, 3.0F).a(cae.T)));
   public static final buo J = a("oak_log", a(cvb.o, cvb.J));
   public static final buo K = a("spruce_log", a(cvb.J, cvb.B));
   public static final buo L = a("birch_log", a(cvb.d, cvb.p));
   public static final buo M = a("jungle_log", a(cvb.l, cvb.J));
   public static final buo N = a("acacia_log", a(cvb.q, cvb.m));
   public static final buo O = a("dark_oak_log", a(cvb.B, cvb.B));
   public static final buo P = a("stripped_spruce_log", a(cvb.J, cvb.J));
   public static final buo Q = a("stripped_birch_log", a(cvb.d, cvb.d));
   public static final buo R = a("stripped_jungle_log", a(cvb.l, cvb.l));
   public static final buo S = a("stripped_acacia_log", a(cvb.q, cvb.q));
   public static final buo T = a("stripped_dark_oak_log", a(cvb.B, cvb.B));
   public static final buo U = a("stripped_oak_log", a(cvb.o, cvb.o));
   public static final buo V = a("oak_wood", new bzl(ceg.c.a(cva.y, cvb.o).d(2.0F).a(cae.a)));
   public static final buo W = a("spruce_wood", new bzl(ceg.c.a(cva.y, cvb.J).d(2.0F).a(cae.a)));
   public static final buo X = a("birch_wood", new bzl(ceg.c.a(cva.y, cvb.d).d(2.0F).a(cae.a)));
   public static final buo Y = a("jungle_wood", new bzl(ceg.c.a(cva.y, cvb.l).d(2.0F).a(cae.a)));
   public static final buo Z = a("acacia_wood", new bzl(ceg.c.a(cva.y, cvb.w).d(2.0F).a(cae.a)));
   public static final buo aa = a("dark_oak_wood", new bzl(ceg.c.a(cva.y, cvb.B).d(2.0F).a(cae.a)));
   public static final buo ab = a("stripped_oak_wood", new bzl(ceg.c.a(cva.y, cvb.o).d(2.0F).a(cae.a)));
   public static final buo ac = a("stripped_spruce_wood", new bzl(ceg.c.a(cva.y, cvb.J).d(2.0F).a(cae.a)));
   public static final buo ad = a("stripped_birch_wood", new bzl(ceg.c.a(cva.y, cvb.d).d(2.0F).a(cae.a)));
   public static final buo ae = a("stripped_jungle_wood", new bzl(ceg.c.a(cva.y, cvb.l).d(2.0F).a(cae.a)));
   public static final buo af = a("stripped_acacia_wood", new bzl(ceg.c.a(cva.y, cvb.q).d(2.0F).a(cae.a)));
   public static final buo ag = a("stripped_dark_oak_wood", new bzl(ceg.c.a(cva.y, cvb.B).d(2.0F).a(cae.a)));
   public static final buo ah = a("oak_leaves", b());
   public static final buo ai = a("spruce_leaves", b());
   public static final buo aj = a("birch_leaves", b());
   public static final buo ak = a("jungle_leaves", b());
   public static final buo al = a("acacia_leaves", b());
   public static final buo am = a("dark_oak_leaves", b());
   public static final buo an = a("sponge", new cag(ceg.c.a(cva.w).d(0.6F).a(cae.c)));
   public static final buo ao = a("wet_sponge", new cbt(ceg.c.a(cva.w).d(0.6F).a(cae.c)));
   public static final buo ap = a("glass", new bwz(ceg.c.a(cva.F).d(0.3F).a(cae.g).b().a(bup::a).a(bup::b).b(bup::b).c(bup::b)));
   public static final buo aq = a("lapis_ore", new byr(ceg.c.a(cva.I).h().a(3.0F, 3.0F)));
   public static final buo ar = a("lapis_block", new buo(ceg.c.a(cva.J, cvb.H).h().a(3.0F, 3.0F)));
   public static final buo as = a("dispenser", new bwa(ceg.c.a(cva.I).h().d(3.5F)));
   public static final buo at = a("sandstone", new buo(ceg.c.a(cva.I, cvb.d).h().d(0.8F)));
   public static final buo au = a("chiseled_sandstone", new buo(ceg.c.a(cva.I, cvb.d).h().d(0.8F)));
   public static final buo av = a("cut_sandstone", new buo(ceg.c.a(cva.I, cvb.d).h().d(0.8F)));
   public static final buo aw = a("note_block", new byo(ceg.c.a(cva.y).a(cae.a).d(0.8F)));
   public static final buo ax = a("white_bed", a(bkx.a));
   public static final buo ay = a("orange_bed", a(bkx.b));
   public static final buo az = a("magenta_bed", a(bkx.c));
   public static final buo aA = a("light_blue_bed", a(bkx.d));
   public static final buo aB = a("yellow_bed", a(bkx.e));
   public static final buo aC = a("lime_bed", a(bkx.f));
   public static final buo aD = a("pink_bed", a(bkx.g));
   public static final buo aE = a("gray_bed", a(bkx.h));
   public static final buo aF = a("light_gray_bed", a(bkx.i));
   public static final buo aG = a("cyan_bed", a(bkx.j));
   public static final buo aH = a("purple_bed", a(bkx.k));
   public static final buo aI = a("blue_bed", a(bkx.l));
   public static final buo aJ = a("brown_bed", a(bkx.m));
   public static final buo aK = a("green_bed", a(bkx.n));
   public static final buo aL = a("red_bed", a(bkx.o));
   public static final buo aM = a("black_bed", a(bkx.p));
   public static final buo aN = a("powered_rail", new byx(ceg.c.a(cva.o).a().d(0.7F).a(cae.f)));
   public static final buo aO = a("detector_rail", new bvx(ceg.c.a(cva.o).a().d(0.7F).a(cae.f)));
   public static final buo aP = a("sticky_piston", a(true));
   public static final buo aQ = a("cobweb", new cbp(ceg.c.a(cva.p).a().h().d(4.0F)));
   public static final buo aR = a("grass", new caw(ceg.c.a(cva.g).a().c().a(cae.c)));
   public static final buo aS = a("fern", new caw(ceg.c.a(cva.g).a().c().a(cae.c)));
   public static final buo aT = a("dead_bush", new bvw(ceg.c.a(cva.g, cvb.o).a().c().a(cae.c)));
   public static final buo aU = a("seagrass", new bzr(ceg.c.a(cva.i).a().c().a(cae.o)));
   public static final buo aV = a("tall_seagrass", new cax(ceg.c.a(cva.i).a().c().a(cae.o)));
   public static final buo aW = a("piston", a(false));
   public static final buo aX = a("piston_head", new ceb(ceg.c.a(cva.N).d(1.5F).f()));
   public static final buo aY = a("white_wool", new buo(ceg.c.a(cva.C, cvb.j).d(0.8F).a(cae.h)));
   public static final buo aZ = a("orange_wool", new buo(ceg.c.a(cva.C, cvb.q).d(0.8F).a(cae.h)));
   public static final buo ba = a("magenta_wool", new buo(ceg.c.a(cva.C, cvb.r).d(0.8F).a(cae.h)));
   public static final buo bb = a("light_blue_wool", new buo(ceg.c.a(cva.C, cvb.s).d(0.8F).a(cae.h)));
   public static final buo bc = a("yellow_wool", new buo(ceg.c.a(cva.C, cvb.t).d(0.8F).a(cae.h)));
   public static final buo bd = a("lime_wool", new buo(ceg.c.a(cva.C, cvb.u).d(0.8F).a(cae.h)));
   public static final buo be = a("pink_wool", new buo(ceg.c.a(cva.C, cvb.v).d(0.8F).a(cae.h)));
   public static final buo bf = a("gray_wool", new buo(ceg.c.a(cva.C, cvb.w).d(0.8F).a(cae.h)));
   public static final buo bg = a("light_gray_wool", new buo(ceg.c.a(cva.C, cvb.x).d(0.8F).a(cae.h)));
   public static final buo bh = a("cyan_wool", new buo(ceg.c.a(cva.C, cvb.y).d(0.8F).a(cae.h)));
   public static final buo bi = a("purple_wool", new buo(ceg.c.a(cva.C, cvb.z).d(0.8F).a(cae.h)));
   public static final buo bj = a("blue_wool", new buo(ceg.c.a(cva.C, cvb.A).d(0.8F).a(cae.h)));
   public static final buo bk = a("brown_wool", new buo(ceg.c.a(cva.C, cvb.B).d(0.8F).a(cae.h)));
   public static final buo bl = a("green_wool", new buo(ceg.c.a(cva.C, cvb.C).d(0.8F).a(cae.h)));
   public static final buo bm = a("red_wool", new buo(ceg.c.a(cva.C, cvb.D).d(0.8F).a(cae.h)));
   public static final buo bn = a("black_wool", new buo(ceg.c.a(cva.C, cvb.E).d(0.8F).a(cae.h)));
   public static final buo bo = a("moving_piston", new cdz(ceg.c.a(cva.N).d(-1.0F).e().f().b().a(bup::b).b(bup::b).c(bup::b)));
   public static final buo bp = a("dandelion", new bwu(apw.w, 7, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo bq = a("poppy", new bwu(apw.p, 5, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo br = a("blue_orchid", new bwu(apw.w, 7, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo bs = a("allium", new bwu(apw.l, 4, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo bt = a("azure_bluet", new bwu(apw.o, 8, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo bu = a("red_tulip", new bwu(apw.r, 9, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo bv = a("orange_tulip", new bwu(apw.r, 9, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo bw = a("white_tulip", new bwu(apw.r, 9, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo bx = a("pink_tulip", new bwu(apw.r, 9, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo by = a("oxeye_daisy", new bwu(apw.j, 8, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo bz = a("cornflower", new bwu(apw.h, 6, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo bA = a("wither_rose", new cbu(apw.t, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo bB = a("lily_of_the_valley", new bwu(apw.s, 12, ceg.c.a(cva.e).a().c().a(cae.c)));
   public static final buo bC = a("brown_mushroom", new byh(ceg.c.a(cva.e, cvb.B).a().d().c().a(cae.c).a(var0 -> 1).d(bup::a)));
   public static final buo bD = a("red_mushroom", new byh(ceg.c.a(cva.e, cvb.D).a().d().c().a(cae.c).d(bup::a)));
   public static final buo bE = a("gold_block", new buo(ceg.c.a(cva.J, cvb.F).h().a(3.0F, 6.0F).a(cae.f)));
   public static final buo bF = a("iron_block", new buo(ceg.c.a(cva.J, cvb.h).h().a(5.0F, 6.0F).a(cae.f)));
   public static final buo bG = a("bricks", new buo(ceg.c.a(cva.I, cvb.D).h().a(2.0F, 6.0F)));
   public static final buo bH = a("tnt", new caz(ceg.c.a(cva.D).c().a(cae.c)));
   public static final buo bI = a("bookshelf", new buo(ceg.c.a(cva.y).d(1.5F).a(cae.a)));
   public static final buo bJ = a("mossy_cobblestone", new buo(ceg.c.a(cva.I).h().a(2.0F, 6.0F)));
   public static final buo bK = a("obsidian", new buo(ceg.c.a(cva.I, cvb.E).h().a(50.0F, 1200.0F)));
   public static final buo bL = a("torch", new cba(ceg.c.a(cva.o).a().c().a(var0 -> 14).a(cae.a), hh.A));
   public static final buo bM = a("wall_torch", new cbn(ceg.c.a(cva.o).a().c().a(var0 -> 14).a(cae.a).a(bL), hh.A));
   public static final buo bN = a("fire", new bws(ceg.c.a(cva.n, cvb.f).a().c().a(var0 -> 15).a(cae.h)));
   public static final buo bO = a("soul_fire", new cac(ceg.c.a(cva.n, cvb.s).a().c().a(var0 -> 10).a(cae.h)));
   public static final buo bP = a("spawner", new caf(ceg.c.a(cva.I).h().d(5.0F).a(cae.f).b()));
   public static final buo bQ = a("oak_stairs", new cak(n.n(), ceg.c.a((ceg)n)));
   public static final buo bR = a("chest", new bve(ceg.c.a(cva.y).d(2.5F).a(cae.a), () -> cck.b));
   public static final buo bS = a("redstone_wire", new bzd(ceg.c.a(cva.o).a().c()));
   public static final buo bT = a("diamond_ore", new byr(ceg.c.a(cva.I).h().a(3.0F, 3.0F)));
   public static final buo bU = a("diamond_block", new buo(ceg.c.a(cva.J, cvb.G).h().a(5.0F, 6.0F).a(cae.f)));
   public static final buo bV = a("crafting_table", new bvr(ceg.c.a(cva.y).d(2.5F).a(cae.a)));
   public static final buo bW = a("wheat", new bvs(ceg.c.a(cva.e).a().d().c().a(cae.u)));
   public static final buo bX = a("farmland", new bwp(ceg.c.a(cva.s).d().d(0.6F).a(cae.b).c(bup::a).b(bup::a)));
   public static final buo bY = a("furnace", new bwy(ceg.c.a(cva.I).h().d(3.5F).a(a(13))));
   public static final buo bZ = a("oak_sign", new cal(ceg.c.a(cva.y).a().d(1.0F).a(cae.a), cfq.a));
   public static final buo ca = a("spruce_sign", new cal(ceg.c.a(cva.y, K.s()).a().d(1.0F).a(cae.a), cfq.b));
   public static final buo cb = a("birch_sign", new cal(ceg.c.a(cva.y, cvb.d).a().d(1.0F).a(cae.a), cfq.c));
   public static final buo cc = a("acacia_sign", new cal(ceg.c.a(cva.y, cvb.q).a().d(1.0F).a(cae.a), cfq.d));
   public static final buo cd = a("jungle_sign", new cal(ceg.c.a(cva.y, M.s()).a().d(1.0F).a(cae.a), cfq.e));
   public static final buo ce = a("dark_oak_sign", new cal(ceg.c.a(cva.y, O.s()).a().d(1.0F).a(cae.a), cfq.f));
   public static final buo cf = a("oak_door", new bwb(ceg.c.a(cva.y, n.s()).d(3.0F).a(cae.a).b()));
   public static final buo cg = a("ladder", new bxv(ceg.c.a(cva.o).d(0.4F).a(cae.k).b()));
   public static final buo ch = a("rail", new bza(ceg.c.a(cva.o).a().d(0.7F).a(cae.f)));
   public static final buo ci = a("cobblestone_stairs", new cak(m.n(), ceg.c.a((ceg)m)));
   public static final buo cj = a("oak_wall_sign", new cbl(ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(bZ), cfq.a));
   public static final buo ck = a("spruce_wall_sign", new cbl(ceg.c.a(cva.y, K.s()).a().d(1.0F).a(cae.a).a(ca), cfq.b));
   public static final buo cl = a("birch_wall_sign", new cbl(ceg.c.a(cva.y, cvb.d).a().d(1.0F).a(cae.a).a(cb), cfq.c));
   public static final buo cm = a("acacia_wall_sign", new cbl(ceg.c.a(cva.y, cvb.q).a().d(1.0F).a(cae.a).a(cc), cfq.d));
   public static final buo cn = a("jungle_wall_sign", new cbl(ceg.c.a(cva.y, M.s()).a().d(1.0F).a(cae.a).a(cd), cfq.e));
   public static final buo co = a("dark_oak_wall_sign", new cbl(ceg.c.a(cva.y, O.s()).a().d(1.0F).a(cae.a).a(ce), cfq.f));
   public static final buo cp = a("lever", new bya(ceg.c.a(cva.o).a().d(0.5F).a(cae.a)));
   public static final buo cq = a("stone_pressure_plate", new byy(byy.a.b, ceg.c.a(cva.I).h().a().d(0.5F)));
   public static final buo cr = a("iron_door", new bwb(ceg.c.a(cva.J, cvb.h).h().d(5.0F).a(cae.f).b()));
   public static final buo cs = a("oak_pressure_plate", new byy(byy.a.a, ceg.c.a(cva.y, n.s()).a().d(0.5F).a(cae.a)));
   public static final buo ct = a("spruce_pressure_plate", new byy(byy.a.a, ceg.c.a(cva.y, o.s()).a().d(0.5F).a(cae.a)));
   public static final buo cu = a("birch_pressure_plate", new byy(byy.a.a, ceg.c.a(cva.y, p.s()).a().d(0.5F).a(cae.a)));
   public static final buo cv = a("jungle_pressure_plate", new byy(byy.a.a, ceg.c.a(cva.y, q.s()).a().d(0.5F).a(cae.a)));
   public static final buo cw = a("acacia_pressure_plate", new byy(byy.a.a, ceg.c.a(cva.y, r.s()).a().d(0.5F).a(cae.a)));
   public static final buo cx = a("dark_oak_pressure_plate", new byy(byy.a.a, ceg.c.a(cva.y, s.s()).a().d(0.5F).a(cae.a)));
   public static final buo cy = a("redstone_ore", new bzc(ceg.c.a(cva.I).h().d().a(a(9)).a(3.0F, 3.0F)));
   public static final buo cz = a("redstone_torch", new bzf(ceg.c.a(cva.o).a().c().a(a(7)).a(cae.a)));
   public static final buo cA = a("redstone_wall_torch", new bzg(ceg.c.a(cva.o).a().c().a(a(7)).a(cae.a).a(cz)));
   public static final buo cB = a("stone_button", new cao(ceg.c.a(cva.o).a().d(0.5F)));
   public static final buo cC = a("snow", new caa(ceg.c.a(cva.m).d().d(0.1F).h().a(cae.j)));
   public static final buo cD = a("ice", new bxo(ceg.c.a(cva.G).a(0.98F).d().d(0.5F).a(cae.g).b().a((var0, var1x, var2x, var3x) -> var3x == aqe.al)));
   public static final buo cE = a("snow_block", new buo(ceg.c.a(cva.K).h().d(0.2F).a(cae.j)));
   public static final buo cF = a("cactus", new buw(ceg.c.a(cva.H).d().d(0.4F).a(cae.h)));
   public static final buo cG = a("clay", new buo(ceg.c.a(cva.r).d(0.6F).a(cae.b)));
   public static final buo cH = a("sugar_cane", new cas(ceg.c.a(cva.e).a().d().c().a(cae.c)));
   public static final buo cI = a("jukebox", new bxs(ceg.c.a(cva.y, cvb.l).a(2.0F, 6.0F)));
   public static final buo cJ = a("oak_fence", new bwq(ceg.c.a(cva.y, n.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo cK = a("pumpkin", new byz(ceg.c.a(cva.P, cvb.q).d(1.0F).a(cae.a)));
   public static final buo cL = a("netherrack", new byn(ceg.c.a(cva.I, cvb.K).h().d(0.4F).a(cae.K)));
   public static final buo cM = a("soul_sand", new cad(ceg.c.a(cva.v, cvb.B).d(0.5F).b(0.4F).a(cae.G).a(bup::b).a(bup::a).c(bup::a).b(bup::a)));
   public static final buo cN = a("soul_soil", new buo(ceg.c.a(cva.s, cvb.B).d(0.5F).a(cae.H)));
   public static final buo cO = a("basalt", new bzl(ceg.c.a(cva.I, cvb.E).h().a(1.25F, 4.2F).a(cae.I)));
   public static final buo cP = a("polished_basalt", new bzl(ceg.c.a(cva.I, cvb.E).h().a(1.25F, 4.2F).a(cae.I)));
   public static final buo cQ = a("soul_torch", new cba(ceg.c.a(cva.o).a().c().a(var0 -> 10).a(cae.a), hh.B));
   public static final buo cR = a("soul_wall_torch", new cbn(ceg.c.a(cva.o).a().c().a(var0 -> 10).a(cae.a).a(cQ), hh.B));
   public static final buo cS = a("glowstone", new buo(ceg.c.a(cva.F, cvb.d).d(0.3F).a(cae.g).a(var0 -> 15)));
   public static final buo cT = a("nether_portal", new byj(ceg.c.a(cva.c).a().d().d(-1.0F).a(cae.g).a(var0 -> 11)));
   public static final buo cU = a("carved_pumpkin", new bvb(ceg.c.a(cva.P, cvb.q).d(1.0F).a(cae.a).a(bup::b)));
   public static final buo cV = a("jack_o_lantern", new bvb(ceg.c.a(cva.P, cvb.q).d(1.0F).a(cae.a).a(var0 -> 15).a(bup::b)));
   public static final buo cW = a("cake", new bux(ceg.c.a(cva.R).d(0.5F).a(cae.h)));
   public static final buo cX = a("repeater", new bzi(ceg.c.a(cva.o).c().a(cae.a)));
   public static final buo cY = a("white_stained_glass", b(bkx.a));
   public static final buo cZ = a("orange_stained_glass", b(bkx.b));
   public static final buo da = a("magenta_stained_glass", b(bkx.c));
   public static final buo db = a("light_blue_stained_glass", b(bkx.d));
   public static final buo dc = a("yellow_stained_glass", b(bkx.e));
   public static final buo dd = a("lime_stained_glass", b(bkx.f));
   public static final buo de = a("pink_stained_glass", b(bkx.g));
   public static final buo df = a("gray_stained_glass", b(bkx.h));
   public static final buo dg = a("light_gray_stained_glass", b(bkx.i));
   public static final buo dh = a("cyan_stained_glass", b(bkx.j));
   public static final buo di = a("purple_stained_glass", b(bkx.k));
   public static final buo dj = a("blue_stained_glass", b(bkx.l));
   public static final buo dk = a("brown_stained_glass", b(bkx.m));
   public static final buo dl = a("green_stained_glass", b(bkx.n));
   public static final buo dm = a("red_stained_glass", b(bkx.o));
   public static final buo dn = a("black_stained_glass", b(bkx.p));
   public static final buo do_ = a("oak_trapdoor", new cbb(ceg.c.a(cva.y, cvb.o).d(3.0F).a(cae.a).b().a(bup::a)));
   public static final buo dp = a("spruce_trapdoor", new cbb(ceg.c.a(cva.y, cvb.J).d(3.0F).a(cae.a).b().a(bup::a)));
   public static final buo dq = a("birch_trapdoor", new cbb(ceg.c.a(cva.y, cvb.d).d(3.0F).a(cae.a).b().a(bup::a)));
   public static final buo dr = a("jungle_trapdoor", new cbb(ceg.c.a(cva.y, cvb.l).d(3.0F).a(cae.a).b().a(bup::a)));
   public static final buo ds = a("acacia_trapdoor", new cbb(ceg.c.a(cva.y, cvb.q).d(3.0F).a(cae.a).b().a(bup::a)));
   public static final buo dt = a("dark_oak_trapdoor", new cbb(ceg.c.a(cva.y, cvb.B).d(3.0F).a(cae.a).b().a(bup::a)));
   public static final buo du = a("stone_bricks", new buo(ceg.c.a(cva.I).h().a(1.5F, 6.0F)));
   public static final buo dv = a("mossy_stone_bricks", new buo(ceg.c.a(cva.I).h().a(1.5F, 6.0F)));
   public static final buo dw = a("cracked_stone_bricks", new buo(ceg.c.a(cva.I).h().a(1.5F, 6.0F)));
   public static final buo dx = a("chiseled_stone_bricks", new buo(ceg.c.a(cva.I).h().a(1.5F, 6.0F)));
   public static final buo dy = a("infested_stone", new bxp(b, ceg.c.a(cva.r).a(0.0F, 0.75F)));
   public static final buo dz = a("infested_cobblestone", new bxp(m, ceg.c.a(cva.r).a(0.0F, 0.75F)));
   public static final buo dA = a("infested_stone_bricks", new bxp(du, ceg.c.a(cva.r).a(0.0F, 0.75F)));
   public static final buo dB = a("infested_mossy_stone_bricks", new bxp(dv, ceg.c.a(cva.r).a(0.0F, 0.75F)));
   public static final buo dC = a("infested_cracked_stone_bricks", new bxp(dw, ceg.c.a(cva.r).a(0.0F, 0.75F)));
   public static final buo dD = a("infested_chiseled_stone_bricks", new bxp(dx, ceg.c.a(cva.r).a(0.0F, 0.75F)));
   public static final buo dE = a("brown_mushroom_block", new bxn(ceg.c.a(cva.y, cvb.l).d(0.2F).a(cae.a)));
   public static final buo dF = a("red_mushroom_block", new bxn(ceg.c.a(cva.y, cvb.D).d(0.2F).a(cae.a)));
   public static final buo dG = a("mushroom_stem", new bxn(ceg.c.a(cva.y, cvb.e).d(0.2F).a(cae.a)));
   public static final buo dH = a("iron_bars", new bxq(ceg.c.a(cva.J, cvb.b).h().a(5.0F, 6.0F).a(cae.f).b()));
   public static final buo dI = a("chain", new bvd(ceg.c.a(cva.J, cvb.b).h().a(5.0F, 6.0F).a(cae.S).b()));
   public static final buo dJ = a("glass_pane", new bxq(ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo dK = a("melon", new byf(ceg.c.a(cva.P, cvb.u).d(1.0F).a(cae.a)));
   public static final buo dL = a("attached_pumpkin_stem", new btt((can)cK, ceg.c.a(cva.e).a().c().a(cae.a)));
   public static final buo dM = a("attached_melon_stem", new btt((can)dK, ceg.c.a(cva.e).a().c().a(cae.a)));
   public static final buo dN = a("pumpkin_stem", new cam((can)cK, ceg.c.a(cva.e).a().d().c().a(cae.v)));
   public static final buo dO = a("melon_stem", new cam((can)dK, ceg.c.a(cva.e).a().d().c().a(cae.v)));
   public static final buo dP = a("vine", new cbi(ceg.c.a(cva.g).a().d().d(0.2F).a(cae.w)));
   public static final buo dQ = a("oak_fence_gate", new bwr(ceg.c.a(cva.y, n.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo dR = a("brick_stairs", new cak(bG.n(), ceg.c.a((ceg)bG)));
   public static final buo dS = a("stone_brick_stairs", new cak(du.n(), ceg.c.a((ceg)du)));
   public static final buo dT = a("mycelium", new byi(ceg.c.a(cva.t, cvb.z).d().d(0.6F).a(cae.c)));
   public static final buo dU = a("lily_pad", new cbo(ceg.c.a(cva.e).c().a(cae.d).b()));
   public static final buo dV = a("nether_bricks", new buo(ceg.c.a(cva.I, cvb.K).h().a(2.0F, 6.0F).a(cae.L)));
   public static final buo dW = a("nether_brick_fence", new bwq(ceg.c.a(cva.I, cvb.K).h().a(2.0F, 6.0F).a(cae.L)));
   public static final buo dX = a("nether_brick_stairs", new cak(dV.n(), ceg.c.a((ceg)dV)));
   public static final buo dY = a("nether_wart", new bym(ceg.c.a(cva.e, cvb.D).a().d().a(cae.x)));
   public static final buo dZ = a("enchanting_table", new bwg(ceg.c.a(cva.I, cvb.D).h().a(5.0F, 1200.0F)));
   public static final buo ea = a("brewing_stand", new bur(ceg.c.a(cva.J).h().d(0.5F).a(var0 -> 1).b()));
   public static final buo eb = a("cauldron", new bvc(ceg.c.a(cva.J, cvb.m).h().d(2.0F).b()));
   public static final buo ec = a("end_portal", new bwi(ceg.c.a(cva.c, cvb.E).a().a(var0 -> 15).a(-1.0F, 3600000.0F).f()));
   public static final buo ed = a("end_portal_frame", new bwj(ceg.c.a(cva.I, cvb.C).a(cae.g).a(var0 -> 1).a(-1.0F, 3600000.0F).f()));
   public static final buo ee = a("end_stone", new buo(ceg.c.a(cva.I, cvb.d).h().a(3.0F, 9.0F)));
   public static final buo ef = a("dragon_egg", new bwe(ceg.c.a(cva.Q, cvb.E).a(3.0F, 9.0F).a(var0 -> 1).b()));
   public static final buo eg = a("redstone_lamp", new bze(ceg.c.a(cva.q).a(a(15)).d(0.3F).a(cae.g).a(bup::b)));
   public static final buo eh = a("cocoa", new bvh(ceg.c.a(cva.e).d().a(0.2F, 3.0F).a(cae.a).b()));
   public static final buo ei = a("sandstone_stairs", new cak(at.n(), ceg.c.a((ceg)at)));
   public static final buo ej = a("emerald_ore", new byr(ceg.c.a(cva.I).h().a(3.0F, 3.0F)));
   public static final buo ek = a("ender_chest", new bwl(ceg.c.a(cva.I).h().a(22.5F, 600.0F).a(var0 -> 7)));
   public static final buo el = a("tripwire_hook", new cbe(ceg.c.a(cva.o).a()));
   public static final buo em = a("tripwire", new cbd((cbe)el, ceg.c.a(cva.o).a()));
   public static final buo en = a("emerald_block", new buo(ceg.c.a(cva.J, cvb.I).h().a(5.0F, 6.0F).a(cae.f)));
   public static final buo eo = a("spruce_stairs", new cak(o.n(), ceg.c.a((ceg)o)));
   public static final buo ep = a("birch_stairs", new cak(p.n(), ceg.c.a((ceg)p)));
   public static final buo eq = a("jungle_stairs", new cak(q.n(), ceg.c.a((ceg)q)));
   public static final buo er = a("command_block", new bvi(ceg.c.a(cva.J, cvb.B).h().a(-1.0F, 3600000.0F).f()));
   public static final buo es = a("beacon", new bui(ceg.c.a(cva.F, cvb.G).d(3.0F).a(var0 -> 15).b().a(bup::b)));
   public static final buo et = a("cobblestone_wall", new cbk(ceg.c.a((ceg)m)));
   public static final buo eu = a("mossy_cobblestone_wall", new cbk(ceg.c.a((ceg)m)));
   public static final buo ev = a("flower_pot", new bwv(a, ceg.c.a(cva.o).c().b()));
   public static final buo ew = a("potted_oak_sapling", new bwv(t, ceg.c.a(cva.o).c().b()));
   public static final buo ex = a("potted_spruce_sapling", new bwv(u, ceg.c.a(cva.o).c().b()));
   public static final buo ey = a("potted_birch_sapling", new bwv(v, ceg.c.a(cva.o).c().b()));
   public static final buo ez = a("potted_jungle_sapling", new bwv(w, ceg.c.a(cva.o).c().b()));
   public static final buo eA = a("potted_acacia_sapling", new bwv(x, ceg.c.a(cva.o).c().b()));
   public static final buo eB = a("potted_dark_oak_sapling", new bwv(y, ceg.c.a(cva.o).c().b()));
   public static final buo eC = a("potted_fern", new bwv(aS, ceg.c.a(cva.o).c().b()));
   public static final buo eD = a("potted_dandelion", new bwv(bp, ceg.c.a(cva.o).c().b()));
   public static final buo eE = a("potted_poppy", new bwv(bq, ceg.c.a(cva.o).c().b()));
   public static final buo eF = a("potted_blue_orchid", new bwv(br, ceg.c.a(cva.o).c().b()));
   public static final buo eG = a("potted_allium", new bwv(bs, ceg.c.a(cva.o).c().b()));
   public static final buo eH = a("potted_azure_bluet", new bwv(bt, ceg.c.a(cva.o).c().b()));
   public static final buo eI = a("potted_red_tulip", new bwv(bu, ceg.c.a(cva.o).c().b()));
   public static final buo eJ = a("potted_orange_tulip", new bwv(bv, ceg.c.a(cva.o).c().b()));
   public static final buo eK = a("potted_white_tulip", new bwv(bw, ceg.c.a(cva.o).c().b()));
   public static final buo eL = a("potted_pink_tulip", new bwv(bx, ceg.c.a(cva.o).c().b()));
   public static final buo eM = a("potted_oxeye_daisy", new bwv(by, ceg.c.a(cva.o).c().b()));
   public static final buo eN = a("potted_cornflower", new bwv(bz, ceg.c.a(cva.o).c().b()));
   public static final buo eO = a("potted_lily_of_the_valley", new bwv(bB, ceg.c.a(cva.o).c().b()));
   public static final buo eP = a("potted_wither_rose", new bwv(bA, ceg.c.a(cva.o).c().b()));
   public static final buo eQ = a("potted_red_mushroom", new bwv(bD, ceg.c.a(cva.o).c().b()));
   public static final buo eR = a("potted_brown_mushroom", new bwv(bC, ceg.c.a(cva.o).c().b()));
   public static final buo eS = a("potted_dead_bush", new bwv(aT, ceg.c.a(cva.o).c().b()));
   public static final buo eT = a("potted_cactus", new bwv(cF, ceg.c.a(cva.o).c().b()));
   public static final buo eU = a("carrots", new buz(ceg.c.a(cva.e).a().d().c().a(cae.u)));
   public static final buo eV = a("potatoes", new byv(ceg.c.a(cva.e).a().d().c().a(cae.u)));
   public static final buo eW = a("oak_button", new cbx(ceg.c.a(cva.o).a().d(0.5F).a(cae.a)));
   public static final buo eX = a("spruce_button", new cbx(ceg.c.a(cva.o).a().d(0.5F).a(cae.a)));
   public static final buo eY = a("birch_button", new cbx(ceg.c.a(cva.o).a().d(0.5F).a(cae.a)));
   public static final buo eZ = a("jungle_button", new cbx(ceg.c.a(cva.o).a().d(0.5F).a(cae.a)));
   public static final buo fa = a("acacia_button", new cbx(ceg.c.a(cva.o).a().d(0.5F).a(cae.a)));
   public static final buo fb = a("dark_oak_button", new cbx(ceg.c.a(cva.o).a().d(0.5F).a(cae.a)));
   public static final buo fc = a("skeleton_skull", new bzv(bzv.b.a, ceg.c.a(cva.o).d(1.0F)));
   public static final buo fd = a("skeleton_wall_skull", new cbm(bzv.b.a, ceg.c.a(cva.o).d(1.0F).a(fc)));
   public static final buo fe = a("wither_skeleton_skull", new cbv(ceg.c.a(cva.o).d(1.0F)));
   public static final buo ff = a("wither_skeleton_wall_skull", new cbw(ceg.c.a(cva.o).d(1.0F).a(fe)));
   public static final buo fg = a("zombie_head", new bzv(bzv.b.d, ceg.c.a(cva.o).d(1.0F)));
   public static final buo fh = a("zombie_wall_head", new cbm(bzv.b.d, ceg.c.a(cva.o).d(1.0F).a(fg)));
   public static final buo fi = a("player_head", new byt(ceg.c.a(cva.o).d(1.0F)));
   public static final buo fj = a("player_wall_head", new byu(ceg.c.a(cva.o).d(1.0F).a(fi)));
   public static final buo fk = a("creeper_head", new bzv(bzv.b.e, ceg.c.a(cva.o).d(1.0F)));
   public static final buo fl = a("creeper_wall_head", new cbm(bzv.b.e, ceg.c.a(cva.o).d(1.0F).a(fk)));
   public static final buo fm = a("dragon_head", new bzv(bzv.b.f, ceg.c.a(cva.o).d(1.0F)));
   public static final buo fn = a("dragon_wall_head", new cbm(bzv.b.f, ceg.c.a(cva.o).d(1.0F).a(fm)));
   public static final buo fo = a("anvil", new bts(ceg.c.a(cva.L, cvb.h).h().a(5.0F, 1200.0F).a(cae.l)));
   public static final buo fp = a("chipped_anvil", new bts(ceg.c.a(cva.L, cvb.h).h().a(5.0F, 1200.0F).a(cae.l)));
   public static final buo fq = a("damaged_anvil", new bts(ceg.c.a(cva.L, cvb.h).h().a(5.0F, 1200.0F).a(cae.l)));
   public static final buo fr = a("trapped_chest", new cbc(ceg.c.a(cva.y).d(2.5F).a(cae.a)));
   public static final buo fs = a("light_weighted_pressure_plate", new cbs(15, ceg.c.a(cva.J, cvb.F).h().a().d(0.5F).a(cae.a)));
   public static final buo ft = a("heavy_weighted_pressure_plate", new cbs(150, ceg.c.a(cva.J).h().a().d(0.5F).a(cae.a)));
   public static final buo fu = a("comparator", new bvj(ceg.c.a(cva.o).c().a(cae.a)));
   public static final buo fv = a("daylight_detector", new bvv(ceg.c.a(cva.y).d(0.2F).a(cae.a)));
   public static final buo fw = a("redstone_block", new byw(ceg.c.a(cva.J, cvb.f).h().a(5.0F, 6.0F).a(cae.f).a(bup::b)));
   public static final buo fx = a("nether_quartz_ore", new byr(ceg.c.a(cva.I, cvb.K).h().a(3.0F, 3.0F).a(cae.N)));
   public static final buo fy = a("hopper", new bxl(ceg.c.a(cva.J, cvb.m).h().a(3.0F, 4.8F).a(cae.f).b()));
   public static final buo fz = a("quartz_block", new buo(ceg.c.a(cva.I, cvb.p).h().d(0.8F)));
   public static final buo fA = a("chiseled_quartz_block", new buo(ceg.c.a(cva.I, cvb.p).h().d(0.8F)));
   public static final buo fB = a("quartz_pillar", new bzl(ceg.c.a(cva.I, cvb.p).h().d(0.8F)));
   public static final buo fC = a("quartz_stairs", new cak(fz.n(), ceg.c.a((ceg)fz)));
   public static final buo fD = a("activator_rail", new byx(ceg.c.a(cva.o).a().d(0.7F).a(cae.f)));
   public static final buo fE = a("dropper", new bwf(ceg.c.a(cva.I).h().d(3.5F)));
   public static final buo fF = a("white_terracotta", new buo(ceg.c.a(cva.I, cvb.L).h().a(1.25F, 4.2F)));
   public static final buo fG = a("orange_terracotta", new buo(ceg.c.a(cva.I, cvb.M).h().a(1.25F, 4.2F)));
   public static final buo fH = a("magenta_terracotta", new buo(ceg.c.a(cva.I, cvb.N).h().a(1.25F, 4.2F)));
   public static final buo fI = a("light_blue_terracotta", new buo(ceg.c.a(cva.I, cvb.O).h().a(1.25F, 4.2F)));
   public static final buo fJ = a("yellow_terracotta", new buo(ceg.c.a(cva.I, cvb.P).h().a(1.25F, 4.2F)));
   public static final buo fK = a("lime_terracotta", new buo(ceg.c.a(cva.I, cvb.Q).h().a(1.25F, 4.2F)));
   public static final buo fL = a("pink_terracotta", new buo(ceg.c.a(cva.I, cvb.R).h().a(1.25F, 4.2F)));
   public static final buo fM = a("gray_terracotta", new buo(ceg.c.a(cva.I, cvb.S).h().a(1.25F, 4.2F)));
   public static final buo fN = a("light_gray_terracotta", new buo(ceg.c.a(cva.I, cvb.T).h().a(1.25F, 4.2F)));
   public static final buo fO = a("cyan_terracotta", new buo(ceg.c.a(cva.I, cvb.U).h().a(1.25F, 4.2F)));
   public static final buo fP = a("purple_terracotta", new buo(ceg.c.a(cva.I, cvb.V).h().a(1.25F, 4.2F)));
   public static final buo fQ = a("blue_terracotta", new buo(ceg.c.a(cva.I, cvb.W).h().a(1.25F, 4.2F)));
   public static final buo fR = a("brown_terracotta", new buo(ceg.c.a(cva.I, cvb.X).h().a(1.25F, 4.2F)));
   public static final buo fS = a("green_terracotta", new buo(ceg.c.a(cva.I, cvb.Y).h().a(1.25F, 4.2F)));
   public static final buo fT = a("red_terracotta", new buo(ceg.c.a(cva.I, cvb.Z).h().a(1.25F, 4.2F)));
   public static final buo fU = a("black_terracotta", new buo(ceg.c.a(cva.I, cvb.aa).h().a(1.25F, 4.2F)));
   public static final buo fV = a("white_stained_glass_pane", new caj(bkx.a, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo fW = a("orange_stained_glass_pane", new caj(bkx.b, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo fX = a("magenta_stained_glass_pane", new caj(bkx.c, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo fY = a("light_blue_stained_glass_pane", new caj(bkx.d, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo fZ = a("yellow_stained_glass_pane", new caj(bkx.e, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo ga = a("lime_stained_glass_pane", new caj(bkx.f, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo gb = a("pink_stained_glass_pane", new caj(bkx.g, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo gc = a("gray_stained_glass_pane", new caj(bkx.h, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo gd = a("light_gray_stained_glass_pane", new caj(bkx.i, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo ge = a("cyan_stained_glass_pane", new caj(bkx.j, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo gf = a("purple_stained_glass_pane", new caj(bkx.k, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo gg = a("blue_stained_glass_pane", new caj(bkx.l, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo gh = a("brown_stained_glass_pane", new caj(bkx.m, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo gi = a("green_stained_glass_pane", new caj(bkx.n, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo gj = a("red_stained_glass_pane", new caj(bkx.o, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo gk = a("black_stained_glass_pane", new caj(bkx.p, ceg.c.a(cva.F).d(0.3F).a(cae.g).b()));
   public static final buo gl = a("acacia_stairs", new cak(r.n(), ceg.c.a((ceg)r)));
   public static final buo gm = a("dark_oak_stairs", new cak(s.n(), ceg.c.a((ceg)s)));
   public static final buo gn = a("slime_block", new bzx(ceg.c.a(cva.r, cvb.c).a(0.8F).a(cae.m).b()));
   public static final buo go = a("barrier", new bty(ceg.c.a(cva.M).a(-1.0F, 3600000.8F).f().b().a(bup::a)));
   public static final buo gp = a("iron_trapdoor", new cbb(ceg.c.a(cva.J).h().d(5.0F).a(cae.f).b().a(bup::a)));
   public static final buo gq = a("prismarine", new buo(ceg.c.a(cva.I, cvb.y).h().a(1.5F, 6.0F)));
   public static final buo gr = a("prismarine_bricks", new buo(ceg.c.a(cva.I, cvb.G).h().a(1.5F, 6.0F)));
   public static final buo gs = a("dark_prismarine", new buo(ceg.c.a(cva.I, cvb.G).h().a(1.5F, 6.0F)));
   public static final buo gt = a("prismarine_stairs", new cak(gq.n(), ceg.c.a((ceg)gq)));
   public static final buo gu = a("prismarine_brick_stairs", new cak(gr.n(), ceg.c.a((ceg)gr)));
   public static final buo gv = a("dark_prismarine_stairs", new cak(gs.n(), ceg.c.a((ceg)gs)));
   public static final buo gw = a("prismarine_slab", new bzw(ceg.c.a(cva.I, cvb.y).h().a(1.5F, 6.0F)));
   public static final buo gx = a("prismarine_brick_slab", new bzw(ceg.c.a(cva.I, cvb.G).h().a(1.5F, 6.0F)));
   public static final buo gy = a("dark_prismarine_slab", new bzw(ceg.c.a(cva.I, cvb.G).h().a(1.5F, 6.0F)));
   public static final buo gz = a("sea_lantern", new buo(ceg.c.a(cva.F, cvb.p).d(0.3F).a(cae.g).a(var0 -> 15)));
   public static final buo gA = a("hay_block", new bxj(ceg.c.a(cva.t, cvb.t).d(0.5F).a(cae.c)));
   public static final buo gB = a("white_carpet", new cby(bkx.a, ceg.c.a(cva.d, cvb.j).d(0.1F).a(cae.h)));
   public static final buo gC = a("orange_carpet", new cby(bkx.b, ceg.c.a(cva.d, cvb.q).d(0.1F).a(cae.h)));
   public static final buo gD = a("magenta_carpet", new cby(bkx.c, ceg.c.a(cva.d, cvb.r).d(0.1F).a(cae.h)));
   public static final buo gE = a("light_blue_carpet", new cby(bkx.d, ceg.c.a(cva.d, cvb.s).d(0.1F).a(cae.h)));
   public static final buo gF = a("yellow_carpet", new cby(bkx.e, ceg.c.a(cva.d, cvb.t).d(0.1F).a(cae.h)));
   public static final buo gG = a("lime_carpet", new cby(bkx.f, ceg.c.a(cva.d, cvb.u).d(0.1F).a(cae.h)));
   public static final buo gH = a("pink_carpet", new cby(bkx.g, ceg.c.a(cva.d, cvb.v).d(0.1F).a(cae.h)));
   public static final buo gI = a("gray_carpet", new cby(bkx.h, ceg.c.a(cva.d, cvb.w).d(0.1F).a(cae.h)));
   public static final buo gJ = a("light_gray_carpet", new cby(bkx.i, ceg.c.a(cva.d, cvb.x).d(0.1F).a(cae.h)));
   public static final buo gK = a("cyan_carpet", new cby(bkx.j, ceg.c.a(cva.d, cvb.y).d(0.1F).a(cae.h)));
   public static final buo gL = a("purple_carpet", new cby(bkx.k, ceg.c.a(cva.d, cvb.z).d(0.1F).a(cae.h)));
   public static final buo gM = a("blue_carpet", new cby(bkx.l, ceg.c.a(cva.d, cvb.A).d(0.1F).a(cae.h)));
   public static final buo gN = a("brown_carpet", new cby(bkx.m, ceg.c.a(cva.d, cvb.B).d(0.1F).a(cae.h)));
   public static final buo gO = a("green_carpet", new cby(bkx.n, ceg.c.a(cva.d, cvb.C).d(0.1F).a(cae.h)));
   public static final buo gP = a("red_carpet", new cby(bkx.o, ceg.c.a(cva.d, cvb.D).d(0.1F).a(cae.h)));
   public static final buo gQ = a("black_carpet", new cby(bkx.p, ceg.c.a(cva.d, cvb.E).d(0.1F).a(cae.h)));
   public static final buo gR = a("terracotta", new buo(ceg.c.a(cva.I, cvb.q).h().a(1.25F, 4.2F)));
   public static final buo gS = a("coal_block", new buo(ceg.c.a(cva.I, cvb.E).h().a(5.0F, 6.0F)));
   public static final buo gT = a("packed_ice", new buo(ceg.c.a(cva.u).a(0.98F).d(0.5F).a(cae.g)));
   public static final buo gU = a("sunflower", new cav(ceg.c.a(cva.g).a().c().a(cae.c)));
   public static final buo gV = a("lilac", new cav(ceg.c.a(cva.g).a().c().a(cae.c)));
   public static final buo gW = a("rose_bush", new cav(ceg.c.a(cva.g).a().c().a(cae.c)));
   public static final buo gX = a("peony", new cav(ceg.c.a(cva.g).a().c().a(cae.c)));
   public static final buo gY = a("tall_grass", new bwd(ceg.c.a(cva.g).a().c().a(cae.c)));
   public static final buo gZ = a("large_fern", new bwd(ceg.c.a(cva.g).a().c().a(cae.c)));
   public static final buo ha = a("white_banner", new btw(bkx.a, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hb = a("orange_banner", new btw(bkx.b, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hc = a("magenta_banner", new btw(bkx.c, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hd = a("light_blue_banner", new btw(bkx.d, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo he = a("yellow_banner", new btw(bkx.e, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hf = a("lime_banner", new btw(bkx.f, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hg = a("pink_banner", new btw(bkx.g, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hh = a("gray_banner", new btw(bkx.h, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hi = a("light_gray_banner", new btw(bkx.i, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hj = a("cyan_banner", new btw(bkx.j, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hk = a("purple_banner", new btw(bkx.k, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hl = a("blue_banner", new btw(bkx.l, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hm = a("brown_banner", new btw(bkx.m, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hn = a("green_banner", new btw(bkx.n, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo ho = a("red_banner", new btw(bkx.o, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hp = a("black_banner", new btw(bkx.p, ceg.c.a(cva.y).a().d(1.0F).a(cae.a)));
   public static final buo hq = a("white_wall_banner", new cbj(bkx.a, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(ha)));
   public static final buo hr = a("orange_wall_banner", new cbj(bkx.b, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hb)));
   public static final buo hs = a("magenta_wall_banner", new cbj(bkx.c, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hc)));
   public static final buo ht = a("light_blue_wall_banner", new cbj(bkx.d, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hd)));
   public static final buo hu = a("yellow_wall_banner", new cbj(bkx.e, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(he)));
   public static final buo hv = a("lime_wall_banner", new cbj(bkx.f, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hf)));
   public static final buo hw = a("pink_wall_banner", new cbj(bkx.g, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hg)));
   public static final buo hx = a("gray_wall_banner", new cbj(bkx.h, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hh)));
   public static final buo hy = a("light_gray_wall_banner", new cbj(bkx.i, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hi)));
   public static final buo hz = a("cyan_wall_banner", new cbj(bkx.j, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hj)));
   public static final buo hA = a("purple_wall_banner", new cbj(bkx.k, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hk)));
   public static final buo hB = a("blue_wall_banner", new cbj(bkx.l, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hl)));
   public static final buo hC = a("brown_wall_banner", new cbj(bkx.m, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hm)));
   public static final buo hD = a("green_wall_banner", new cbj(bkx.n, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hn)));
   public static final buo hE = a("red_wall_banner", new cbj(bkx.o, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(ho)));
   public static final buo hF = a("black_wall_banner", new cbj(bkx.p, ceg.c.a(cva.y).a().d(1.0F).a(cae.a).a(hp)));
   public static final buo hG = a("red_sandstone", new buo(ceg.c.a(cva.I, cvb.q).h().d(0.8F)));
   public static final buo hH = a("chiseled_red_sandstone", new buo(ceg.c.a(cva.I, cvb.q).h().d(0.8F)));
   public static final buo hI = a("cut_red_sandstone", new buo(ceg.c.a(cva.I, cvb.q).h().d(0.8F)));
   public static final buo hJ = a("red_sandstone_stairs", new cak(hG.n(), ceg.c.a((ceg)hG)));
   public static final buo hK = a("oak_slab", new bzw(ceg.c.a(cva.y, cvb.o).a(2.0F, 3.0F).a(cae.a)));
   public static final buo hL = a("spruce_slab", new bzw(ceg.c.a(cva.y, cvb.J).a(2.0F, 3.0F).a(cae.a)));
   public static final buo hM = a("birch_slab", new bzw(ceg.c.a(cva.y, cvb.d).a(2.0F, 3.0F).a(cae.a)));
   public static final buo hN = a("jungle_slab", new bzw(ceg.c.a(cva.y, cvb.l).a(2.0F, 3.0F).a(cae.a)));
   public static final buo hO = a("acacia_slab", new bzw(ceg.c.a(cva.y, cvb.q).a(2.0F, 3.0F).a(cae.a)));
   public static final buo hP = a("dark_oak_slab", new bzw(ceg.c.a(cva.y, cvb.B).a(2.0F, 3.0F).a(cae.a)));
   public static final buo hQ = a("stone_slab", new bzw(ceg.c.a(cva.I, cvb.m).h().a(2.0F, 6.0F)));
   public static final buo hR = a("smooth_stone_slab", new bzw(ceg.c.a(cva.I, cvb.m).h().a(2.0F, 6.0F)));
   public static final buo hS = a("sandstone_slab", new bzw(ceg.c.a(cva.I, cvb.d).h().a(2.0F, 6.0F)));
   public static final buo hT = a("cut_sandstone_slab", new bzw(ceg.c.a(cva.I, cvb.d).h().a(2.0F, 6.0F)));
   public static final buo hU = a("petrified_oak_slab", new bzw(ceg.c.a(cva.I, cvb.o).h().a(2.0F, 6.0F)));
   public static final buo hV = a("cobblestone_slab", new bzw(ceg.c.a(cva.I, cvb.m).h().a(2.0F, 6.0F)));
   public static final buo hW = a("brick_slab", new bzw(ceg.c.a(cva.I, cvb.D).h().a(2.0F, 6.0F)));
   public static final buo hX = a("stone_brick_slab", new bzw(ceg.c.a(cva.I, cvb.m).h().a(2.0F, 6.0F)));
   public static final buo hY = a("nether_brick_slab", new bzw(ceg.c.a(cva.I, cvb.K).h().a(2.0F, 6.0F).a(cae.L)));
   public static final buo hZ = a("quartz_slab", new bzw(ceg.c.a(cva.I, cvb.p).h().a(2.0F, 6.0F)));
   public static final buo ia = a("red_sandstone_slab", new bzw(ceg.c.a(cva.I, cvb.q).h().a(2.0F, 6.0F)));
   public static final buo ib = a("cut_red_sandstone_slab", new bzw(ceg.c.a(cva.I, cvb.q).h().a(2.0F, 6.0F)));
   public static final buo ic = a("purpur_slab", new bzw(ceg.c.a(cva.I, cvb.r).h().a(2.0F, 6.0F)));
   public static final buo id = a("smooth_stone", new buo(ceg.c.a(cva.I, cvb.m).h().a(2.0F, 6.0F)));
   public static final buo ie = a("smooth_sandstone", new buo(ceg.c.a(cva.I, cvb.d).h().a(2.0F, 6.0F)));
   public static final buo if_ = a("smooth_quartz", new buo(ceg.c.a(cva.I, cvb.p).h().a(2.0F, 6.0F)));
   public static final buo ig = a("smooth_red_sandstone", new buo(ceg.c.a(cva.I, cvb.q).h().a(2.0F, 6.0F)));
   public static final buo ih = a("spruce_fence_gate", new bwr(ceg.c.a(cva.y, o.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo ii = a("birch_fence_gate", new bwr(ceg.c.a(cva.y, p.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo ij = a("jungle_fence_gate", new bwr(ceg.c.a(cva.y, q.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo ik = a("acacia_fence_gate", new bwr(ceg.c.a(cva.y, r.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo il = a("dark_oak_fence_gate", new bwr(ceg.c.a(cva.y, s.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo im = a("spruce_fence", new bwq(ceg.c.a(cva.y, o.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo in = a("birch_fence", new bwq(ceg.c.a(cva.y, p.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo io = a("jungle_fence", new bwq(ceg.c.a(cva.y, q.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo ip = a("acacia_fence", new bwq(ceg.c.a(cva.y, r.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo iq = a("dark_oak_fence", new bwq(ceg.c.a(cva.y, s.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo ir = a("spruce_door", new bwb(ceg.c.a(cva.y, o.s()).d(3.0F).a(cae.a).b()));
   public static final buo is = a("birch_door", new bwb(ceg.c.a(cva.y, p.s()).d(3.0F).a(cae.a).b()));
   public static final buo it = a("jungle_door", new bwb(ceg.c.a(cva.y, q.s()).d(3.0F).a(cae.a).b()));
   public static final buo iu = a("acacia_door", new bwb(ceg.c.a(cva.y, r.s()).d(3.0F).a(cae.a).b()));
   public static final buo iv = a("dark_oak_door", new bwb(ceg.c.a(cva.y, s.s()).d(3.0F).a(cae.a).b()));
   public static final buo iw = a("end_rod", new bwk(ceg.c.a(cva.o).c().a(var0 -> 14).a(cae.a).b()));
   public static final buo ix = a("chorus_plant", new bvg(ceg.c.a(cva.e, cvb.z).d(0.4F).a(cae.a).b()));
   public static final buo iy = a("chorus_flower", new bvf((bvg)ix, ceg.c.a(cva.e, cvb.z).d().d(0.4F).a(cae.a).b()));
   public static final buo iz = a("purpur_block", new buo(ceg.c.a(cva.I, cvb.r).h().a(1.5F, 6.0F)));
   public static final buo iA = a("purpur_pillar", new bzl(ceg.c.a(cva.I, cvb.r).h().a(1.5F, 6.0F)));
   public static final buo iB = a("purpur_stairs", new cak(iz.n(), ceg.c.a((ceg)iz)));
   public static final buo iC = a("end_stone_bricks", new buo(ceg.c.a(cva.I, cvb.d).h().a(3.0F, 9.0F)));
   public static final buo iD = a("beetroots", new bul(ceg.c.a(cva.e).a().d().c().a(cae.u)));
   public static final buo iE = a("grass_path", new bxc(ceg.c.a(cva.s).d(0.65F).a(cae.c).c(bup::a).b(bup::a)));
   public static final buo iF = a("end_gateway", new bwh(ceg.c.a(cva.c, cvb.E).a().a(var0 -> 15).a(-1.0F, 3600000.0F).f()));
   public static final buo iG = a("repeating_command_block", new bvi(ceg.c.a(cva.J, cvb.z).h().a(-1.0F, 3600000.0F).f()));
   public static final buo iH = a("chain_command_block", new bvi(ceg.c.a(cva.J, cvb.C).h().a(-1.0F, 3600000.0F).f()));
   public static final buo iI = a("frosted_ice", new bww(ceg.c.a(cva.G).a(0.98F).d().d(0.5F).a(cae.g).b().a((var0, var1x, var2x, var3x) -> var3x == aqe.al)));
   public static final buo iJ = a(
      "magma_block", new bye(ceg.c.a(cva.I, cvb.K).h().a(var0 -> 3).d().d(0.5F).a((var0, var1x, var2x, var3x) -> var3x.c()).d(bup::a).e(bup::a))
   );
   public static final buo iK = a("nether_wart_block", new buo(ceg.c.a(cva.t, cvb.D).d(1.0F).a(cae.J)));
   public static final buo iL = a("red_nether_bricks", new buo(ceg.c.a(cva.I, cvb.K).h().a(2.0F, 6.0F).a(cae.L)));
   public static final buo iM = a("bone_block", new bzl(ceg.c.a(cva.I, cvb.d).h().d(2.0F).a(cae.O)));
   public static final buo iN = a("structure_void", new car(ceg.c.a(cva.b).a().f()));
   public static final buo iO = a("observer", new byq(ceg.c.a(cva.I).d(3.0F).h().a(bup::b)));
   public static final buo iP = a("shulker_box", a(null, ceg.c.a(cva.x)));
   public static final buo iQ = a("white_shulker_box", a(bkx.a, ceg.c.a(cva.x, cvb.j)));
   public static final buo iR = a("orange_shulker_box", a(bkx.b, ceg.c.a(cva.x, cvb.q)));
   public static final buo iS = a("magenta_shulker_box", a(bkx.c, ceg.c.a(cva.x, cvb.r)));
   public static final buo iT = a("light_blue_shulker_box", a(bkx.d, ceg.c.a(cva.x, cvb.s)));
   public static final buo iU = a("yellow_shulker_box", a(bkx.e, ceg.c.a(cva.x, cvb.t)));
   public static final buo iV = a("lime_shulker_box", a(bkx.f, ceg.c.a(cva.x, cvb.u)));
   public static final buo iW = a("pink_shulker_box", a(bkx.g, ceg.c.a(cva.x, cvb.v)));
   public static final buo iX = a("gray_shulker_box", a(bkx.h, ceg.c.a(cva.x, cvb.w)));
   public static final buo iY = a("light_gray_shulker_box", a(bkx.i, ceg.c.a(cva.x, cvb.x)));
   public static final buo iZ = a("cyan_shulker_box", a(bkx.j, ceg.c.a(cva.x, cvb.y)));
   public static final buo ja = a("purple_shulker_box", a(bkx.k, ceg.c.a(cva.x, cvb.V)));
   public static final buo jb = a("blue_shulker_box", a(bkx.l, ceg.c.a(cva.x, cvb.A)));
   public static final buo jc = a("brown_shulker_box", a(bkx.m, ceg.c.a(cva.x, cvb.B)));
   public static final buo jd = a("green_shulker_box", a(bkx.n, ceg.c.a(cva.x, cvb.C)));
   public static final buo je = a("red_shulker_box", a(bkx.o, ceg.c.a(cva.x, cvb.D)));
   public static final buo jf = a("black_shulker_box", a(bkx.p, ceg.c.a(cva.x, cvb.E)));
   public static final buo jg = a("white_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.a).h().d(1.4F)));
   public static final buo jh = a("orange_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.b).h().d(1.4F)));
   public static final buo ji = a("magenta_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.c).h().d(1.4F)));
   public static final buo jj = a("light_blue_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.d).h().d(1.4F)));
   public static final buo jk = a("yellow_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.e).h().d(1.4F)));
   public static final buo jl = a("lime_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.f).h().d(1.4F)));
   public static final buo jm = a("pink_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.g).h().d(1.4F)));
   public static final buo jn = a("gray_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.h).h().d(1.4F)));
   public static final buo jo = a("light_gray_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.i).h().d(1.4F)));
   public static final buo jp = a("cyan_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.j).h().d(1.4F)));
   public static final buo jq = a("purple_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.k).h().d(1.4F)));
   public static final buo jr = a("blue_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.l).h().d(1.4F)));
   public static final buo js = a("brown_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.m).h().d(1.4F)));
   public static final buo jt = a("green_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.n).h().d(1.4F)));
   public static final buo ju = a("red_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.o).h().d(1.4F)));
   public static final buo jv = a("black_glazed_terracotta", new bxa(ceg.c.a(cva.I, bkx.p).h().d(1.4F)));
   public static final buo jw = a("white_concrete", new buo(ceg.c.a(cva.I, bkx.a).h().d(1.8F)));
   public static final buo jx = a("orange_concrete", new buo(ceg.c.a(cva.I, bkx.b).h().d(1.8F)));
   public static final buo jy = a("magenta_concrete", new buo(ceg.c.a(cva.I, bkx.c).h().d(1.8F)));
   public static final buo jz = a("light_blue_concrete", new buo(ceg.c.a(cva.I, bkx.d).h().d(1.8F)));
   public static final buo jA = a("yellow_concrete", new buo(ceg.c.a(cva.I, bkx.e).h().d(1.8F)));
   public static final buo jB = a("lime_concrete", new buo(ceg.c.a(cva.I, bkx.f).h().d(1.8F)));
   public static final buo jC = a("pink_concrete", new buo(ceg.c.a(cva.I, bkx.g).h().d(1.8F)));
   public static final buo jD = a("gray_concrete", new buo(ceg.c.a(cva.I, bkx.h).h().d(1.8F)));
   public static final buo jE = a("light_gray_concrete", new buo(ceg.c.a(cva.I, bkx.i).h().d(1.8F)));
   public static final buo jF = a("cyan_concrete", new buo(ceg.c.a(cva.I, bkx.j).h().d(1.8F)));
   public static final buo jG = a("purple_concrete", new buo(ceg.c.a(cva.I, bkx.k).h().d(1.8F)));
   public static final buo jH = a("blue_concrete", new buo(ceg.c.a(cva.I, bkx.l).h().d(1.8F)));
   public static final buo jI = a("brown_concrete", new buo(ceg.c.a(cva.I, bkx.m).h().d(1.8F)));
   public static final buo jJ = a("green_concrete", new buo(ceg.c.a(cva.I, bkx.n).h().d(1.8F)));
   public static final buo jK = a("red_concrete", new buo(ceg.c.a(cva.I, bkx.o).h().d(1.8F)));
   public static final buo jL = a("black_concrete", new buo(ceg.c.a(cva.I, bkx.p).h().d(1.8F)));
   public static final buo jM = a("white_concrete_powder", new bvl(jw, ceg.c.a(cva.v, bkx.a).d(0.5F).a(cae.i)));
   public static final buo jN = a("orange_concrete_powder", new bvl(jx, ceg.c.a(cva.v, bkx.b).d(0.5F).a(cae.i)));
   public static final buo jO = a("magenta_concrete_powder", new bvl(jy, ceg.c.a(cva.v, bkx.c).d(0.5F).a(cae.i)));
   public static final buo jP = a("light_blue_concrete_powder", new bvl(jz, ceg.c.a(cva.v, bkx.d).d(0.5F).a(cae.i)));
   public static final buo jQ = a("yellow_concrete_powder", new bvl(jA, ceg.c.a(cva.v, bkx.e).d(0.5F).a(cae.i)));
   public static final buo jR = a("lime_concrete_powder", new bvl(jB, ceg.c.a(cva.v, bkx.f).d(0.5F).a(cae.i)));
   public static final buo jS = a("pink_concrete_powder", new bvl(jC, ceg.c.a(cva.v, bkx.g).d(0.5F).a(cae.i)));
   public static final buo jT = a("gray_concrete_powder", new bvl(jD, ceg.c.a(cva.v, bkx.h).d(0.5F).a(cae.i)));
   public static final buo jU = a("light_gray_concrete_powder", new bvl(jE, ceg.c.a(cva.v, bkx.i).d(0.5F).a(cae.i)));
   public static final buo jV = a("cyan_concrete_powder", new bvl(jF, ceg.c.a(cva.v, bkx.j).d(0.5F).a(cae.i)));
   public static final buo jW = a("purple_concrete_powder", new bvl(jG, ceg.c.a(cva.v, bkx.k).d(0.5F).a(cae.i)));
   public static final buo jX = a("blue_concrete_powder", new bvl(jH, ceg.c.a(cva.v, bkx.l).d(0.5F).a(cae.i)));
   public static final buo jY = a("brown_concrete_powder", new bvl(jI, ceg.c.a(cva.v, bkx.m).d(0.5F).a(cae.i)));
   public static final buo jZ = a("green_concrete_powder", new bvl(jJ, ceg.c.a(cva.v, bkx.n).d(0.5F).a(cae.i)));
   public static final buo ka = a("red_concrete_powder", new bvl(jK, ceg.c.a(cva.v, bkx.o).d(0.5F).a(cae.i)));
   public static final buo kb = a("black_concrete_powder", new bvl(jL, ceg.c.a(cva.v, bkx.p).d(0.5F).a(cae.i)));
   public static final buo kc = a("kelp", new bxt(ceg.c.a(cva.f).a().d().c().a(cae.o)));
   public static final buo kd = a("kelp_plant", new bxu(ceg.c.a(cva.f).a().c().a(cae.o)));
   public static final buo ke = a("dried_kelp_block", new buo(ceg.c.a(cva.t, cvb.C).a(0.5F, 2.5F).a(cae.c)));
   public static final buo kf = a("turtle_egg", new cbf(ceg.c.a(cva.Q, cvb.d).d(0.5F).a(cae.f).d().b()));
   public static final buo kg = a("dead_tube_coral_block", new buo(ceg.c.a(cva.I, cvb.w).h().a(1.5F, 6.0F)));
   public static final buo kh = a("dead_brain_coral_block", new buo(ceg.c.a(cva.I, cvb.w).h().a(1.5F, 6.0F)));
   public static final buo ki = a("dead_bubble_coral_block", new buo(ceg.c.a(cva.I, cvb.w).h().a(1.5F, 6.0F)));
   public static final buo kj = a("dead_fire_coral_block", new buo(ceg.c.a(cva.I, cvb.w).h().a(1.5F, 6.0F)));
   public static final buo kk = a("dead_horn_coral_block", new buo(ceg.c.a(cva.I, cvb.w).h().a(1.5F, 6.0F)));
   public static final buo kl = a("tube_coral_block", new bvn(kg, ceg.c.a(cva.I, cvb.A).h().a(1.5F, 6.0F).a(cae.p)));
   public static final buo km = a("brain_coral_block", new bvn(kh, ceg.c.a(cva.I, cvb.v).h().a(1.5F, 6.0F).a(cae.p)));
   public static final buo kn = a("bubble_coral_block", new bvn(ki, ceg.c.a(cva.I, cvb.z).h().a(1.5F, 6.0F).a(cae.p)));
   public static final buo ko = a("fire_coral_block", new bvn(kj, ceg.c.a(cva.I, cvb.D).h().a(1.5F, 6.0F).a(cae.p)));
   public static final buo kp = a("horn_coral_block", new bvn(kk, ceg.c.a(cva.I, cvb.t).h().a(1.5F, 6.0F).a(cae.p)));
   public static final buo kq = a("dead_tube_coral", new bua(ceg.c.a(cva.I, cvb.w).h().a().c()));
   public static final buo kr = a("dead_brain_coral", new bua(ceg.c.a(cva.I, cvb.w).h().a().c()));
   public static final buo ks = a("dead_bubble_coral", new bua(ceg.c.a(cva.I, cvb.w).h().a().c()));
   public static final buo kt = a("dead_fire_coral", new bua(ceg.c.a(cva.I, cvb.w).h().a().c()));
   public static final buo ku = a("dead_horn_coral", new bua(ceg.c.a(cva.I, cvb.w).h().a().c()));
   public static final buo kv = a("tube_coral", new bvp(kq, ceg.c.a(cva.f, cvb.A).a().c().a(cae.o)));
   public static final buo kw = a("brain_coral", new bvp(kr, ceg.c.a(cva.f, cvb.v).a().c().a(cae.o)));
   public static final buo kx = a("bubble_coral", new bvp(ks, ceg.c.a(cva.f, cvb.z).a().c().a(cae.o)));
   public static final buo ky = a("fire_coral", new bvp(kt, ceg.c.a(cva.f, cvb.D).a().c().a(cae.o)));
   public static final buo kz = a("horn_coral", new bvp(ku, ceg.c.a(cva.f, cvb.t).a().c().a(cae.o)));
   public static final buo kA = a("dead_tube_coral_fan", new btz(ceg.c.a(cva.I, cvb.w).h().a().c()));
   public static final buo kB = a("dead_brain_coral_fan", new btz(ceg.c.a(cva.I, cvb.w).h().a().c()));
   public static final buo kC = a("dead_bubble_coral_fan", new btz(ceg.c.a(cva.I, cvb.w).h().a().c()));
   public static final buo kD = a("dead_fire_coral_fan", new btz(ceg.c.a(cva.I, cvb.w).h().a().c()));
   public static final buo kE = a("dead_horn_coral_fan", new btz(ceg.c.a(cva.I, cvb.w).h().a().c()));
   public static final buo kF = a("tube_coral_fan", new bvo(kA, ceg.c.a(cva.f, cvb.A).a().c().a(cae.o)));
   public static final buo kG = a("brain_coral_fan", new bvo(kB, ceg.c.a(cva.f, cvb.v).a().c().a(cae.o)));
   public static final buo kH = a("bubble_coral_fan", new bvo(kC, ceg.c.a(cva.f, cvb.z).a().c().a(cae.o)));
   public static final buo kI = a("fire_coral_fan", new bvo(kD, ceg.c.a(cva.f, cvb.D).a().c().a(cae.o)));
   public static final buo kJ = a("horn_coral_fan", new bvo(kE, ceg.c.a(cva.f, cvb.t).a().c().a(cae.o)));
   public static final buo kK = a("dead_tube_coral_wall_fan", new buc(ceg.c.a(cva.I, cvb.w).h().a().c().a(kA)));
   public static final buo kL = a("dead_brain_coral_wall_fan", new buc(ceg.c.a(cva.I, cvb.w).h().a().c().a(kB)));
   public static final buo kM = a("dead_bubble_coral_wall_fan", new buc(ceg.c.a(cva.I, cvb.w).h().a().c().a(kC)));
   public static final buo kN = a("dead_fire_coral_wall_fan", new buc(ceg.c.a(cva.I, cvb.w).h().a().c().a(kD)));
   public static final buo kO = a("dead_horn_coral_wall_fan", new buc(ceg.c.a(cva.I, cvb.w).h().a().c().a(kE)));
   public static final buo kP = a("tube_coral_wall_fan", new bvq(kK, ceg.c.a(cva.f, cvb.A).a().c().a(cae.o).a(kF)));
   public static final buo kQ = a("brain_coral_wall_fan", new bvq(kL, ceg.c.a(cva.f, cvb.v).a().c().a(cae.o).a(kG)));
   public static final buo kR = a("bubble_coral_wall_fan", new bvq(kM, ceg.c.a(cva.f, cvb.z).a().c().a(cae.o).a(kH)));
   public static final buo kS = a("fire_coral_wall_fan", new bvq(kN, ceg.c.a(cva.f, cvb.D).a().c().a(cae.o).a(kI)));
   public static final buo kT = a("horn_coral_wall_fan", new bvq(kO, ceg.c.a(cva.f, cvb.t).a().c().a(cae.o).a(kJ)));
   public static final buo kU = a("sea_pickle", new bzq(ceg.c.a(cva.f, cvb.C).a(var0 -> bzq.h(var0) ? 0 : 3 + 3 * var0.c(bzq.a)).a(cae.m).b()));
   public static final buo kV = a("blue_ice", new bxi(ceg.c.a(cva.u).d(2.8F).a(0.989F).a(cae.g)));
   public static final buo kW = a("conduit", new bvm(ceg.c.a(cva.F, cvb.G).d(3.0F).a(var0 -> 15).b()));
   public static final buo kX = a("bamboo_sapling", new btv(ceg.c.a(cva.A).d().c().a().d(1.0F).a(cae.r)));
   public static final buo kY = a("bamboo", new btu(ceg.c.a(cva.B, cvb.i).d().c().d(1.0F).a(cae.q).b()));
   public static final buo kZ = a("potted_bamboo", new bwv(kY, ceg.c.a(cva.o).c().b()));
   public static final buo la = a("void_air", new btr(ceg.c.a(cva.a).a().f().g()));
   public static final buo lb = a("cave_air", new btr(ceg.c.a(cva.a).a().f().g()));
   public static final buo lc = a("bubble_column", new bus(ceg.c.a(cva.k).a().f()));
   public static final buo ld = a("polished_granite_stairs", new cak(d.n(), ceg.c.a((ceg)d)));
   public static final buo le = a("smooth_red_sandstone_stairs", new cak(ig.n(), ceg.c.a((ceg)ig)));
   public static final buo lf = a("mossy_stone_brick_stairs", new cak(dv.n(), ceg.c.a((ceg)dv)));
   public static final buo lg = a("polished_diorite_stairs", new cak(f.n(), ceg.c.a((ceg)f)));
   public static final buo lh = a("mossy_cobblestone_stairs", new cak(bJ.n(), ceg.c.a((ceg)bJ)));
   public static final buo li = a("end_stone_brick_stairs", new cak(iC.n(), ceg.c.a((ceg)iC)));
   public static final buo lj = a("stone_stairs", new cak(b.n(), ceg.c.a((ceg)b)));
   public static final buo lk = a("smooth_sandstone_stairs", new cak(ie.n(), ceg.c.a((ceg)ie)));
   public static final buo ll = a("smooth_quartz_stairs", new cak(if_.n(), ceg.c.a((ceg)if_)));
   public static final buo lm = a("granite_stairs", new cak(c.n(), ceg.c.a((ceg)c)));
   public static final buo ln = a("andesite_stairs", new cak(g.n(), ceg.c.a((ceg)g)));
   public static final buo lo = a("red_nether_brick_stairs", new cak(iL.n(), ceg.c.a((ceg)iL)));
   public static final buo lp = a("polished_andesite_stairs", new cak(h.n(), ceg.c.a((ceg)h)));
   public static final buo lq = a("diorite_stairs", new cak(e.n(), ceg.c.a((ceg)e)));
   public static final buo lr = a("polished_granite_slab", new bzw(ceg.c.a((ceg)d)));
   public static final buo ls = a("smooth_red_sandstone_slab", new bzw(ceg.c.a((ceg)ig)));
   public static final buo lt = a("mossy_stone_brick_slab", new bzw(ceg.c.a((ceg)dv)));
   public static final buo lu = a("polished_diorite_slab", new bzw(ceg.c.a((ceg)f)));
   public static final buo lv = a("mossy_cobblestone_slab", new bzw(ceg.c.a((ceg)bJ)));
   public static final buo lw = a("end_stone_brick_slab", new bzw(ceg.c.a((ceg)iC)));
   public static final buo lx = a("smooth_sandstone_slab", new bzw(ceg.c.a((ceg)ie)));
   public static final buo ly = a("smooth_quartz_slab", new bzw(ceg.c.a((ceg)if_)));
   public static final buo lz = a("granite_slab", new bzw(ceg.c.a((ceg)c)));
   public static final buo lA = a("andesite_slab", new bzw(ceg.c.a((ceg)g)));
   public static final buo lB = a("red_nether_brick_slab", new bzw(ceg.c.a((ceg)iL)));
   public static final buo lC = a("polished_andesite_slab", new bzw(ceg.c.a((ceg)h)));
   public static final buo lD = a("diorite_slab", new bzw(ceg.c.a((ceg)e)));
   public static final buo lE = a("brick_wall", new cbk(ceg.c.a((ceg)bG)));
   public static final buo lF = a("prismarine_wall", new cbk(ceg.c.a((ceg)gq)));
   public static final buo lG = a("red_sandstone_wall", new cbk(ceg.c.a((ceg)hG)));
   public static final buo lH = a("mossy_stone_brick_wall", new cbk(ceg.c.a((ceg)dv)));
   public static final buo lI = a("granite_wall", new cbk(ceg.c.a((ceg)c)));
   public static final buo lJ = a("stone_brick_wall", new cbk(ceg.c.a((ceg)du)));
   public static final buo lK = a("nether_brick_wall", new cbk(ceg.c.a((ceg)dV)));
   public static final buo lL = a("andesite_wall", new cbk(ceg.c.a((ceg)g)));
   public static final buo lM = a("red_nether_brick_wall", new cbk(ceg.c.a((ceg)iL)));
   public static final buo lN = a("sandstone_wall", new cbk(ceg.c.a((ceg)at)));
   public static final buo lO = a("end_stone_brick_wall", new cbk(ceg.c.a((ceg)iC)));
   public static final buo lP = a("diorite_wall", new cbk(ceg.c.a((ceg)e)));
   public static final buo lQ = a("scaffolding", new bzp(ceg.c.a(cva.o, cvb.d).a().a(cae.s).e()));
   public static final buo lR = a("loom", new byd(ceg.c.a(cva.y).d(2.5F).a(cae.a)));
   public static final buo lS = a("barrel", new btx(ceg.c.a(cva.y).d(2.5F).a(cae.a)));
   public static final buo lT = a("smoker", new bzz(ceg.c.a(cva.I).h().d(3.5F).a(a(13))));
   public static final buo lU = a("blast_furnace", new bun(ceg.c.a(cva.I).h().d(3.5F).a(a(13))));
   public static final buo lV = a("cartography_table", new bva(ceg.c.a(cva.y).d(2.5F).a(cae.a)));
   public static final buo lW = a("fletching_table", new bwt(ceg.c.a(cva.y).d(2.5F).a(cae.a)));
   public static final buo lX = a("grindstone", new bxe(ceg.c.a(cva.L, cvb.h).h().a(2.0F, 6.0F).a(cae.e)));
   public static final buo lY = a("lectern", new bxy(ceg.c.a(cva.y).d(2.5F).a(cae.a)));
   public static final buo lZ = a("smithing_table", new bzy(ceg.c.a(cva.y).d(2.5F).a(cae.a)));
   public static final buo ma = a("stonecutter", new cap(ceg.c.a(cva.I).h().d(3.5F)));
   public static final buo mb = a("bell", new bum(ceg.c.a(cva.J, cvb.F).h().d(5.0F).a(cae.l)));
   public static final buo mc = a("lantern", new bxw(ceg.c.a(cva.J).h().d(3.5F).a(cae.y).a(var0 -> 15).b()));
   public static final buo md = a("soul_lantern", new bxw(ceg.c.a(cva.J).h().d(3.5F).a(cae.y).a(var0 -> 10).b()));
   public static final buo me = a("campfire", new buy(true, 1, ceg.c.a(cva.y, cvb.J).d(2.0F).a(cae.a).a(a(15)).b()));
   public static final buo mf = a("soul_campfire", new buy(false, 2, ceg.c.a(cva.y, cvb.J).d(2.0F).a(cae.a).a(a(10)).b()));
   public static final buo mg = a("sweet_berry_bush", new cau(ceg.c.a(cva.e).d().a().a(cae.t)));
   public static final buo mh = a("warped_stem", a(cvb.af));
   public static final buo mi = a("stripped_warped_stem", a(cvb.af));
   public static final buo mj = a("warped_hyphae", new bzl(ceg.c.a(cva.z, cvb.ag).d(2.0F).a(cae.z)));
   public static final buo mk = a("stripped_warped_hyphae", new bzl(ceg.c.a(cva.z, cvb.ag).d(2.0F).a(cae.z)));
   public static final buo ml = a("warped_nylium", new byp(ceg.c.a(cva.I, cvb.ae).h().d(0.4F).a(cae.A).d()));
   public static final buo mm = a("warped_fungus", new bwx(ceg.c.a(cva.e, cvb.y).c().a().a(cae.B), () -> kh.bE));
   public static final buo mn = a("warped_wart_block", new buo(ceg.c.a(cva.t, cvb.ah).d(1.0F).a(cae.J)));
   public static final buo mo = a("warped_roots", new bzk(ceg.c.a(cva.h, cvb.y).a().c().a(cae.C)));
   public static final buo mp = a("nether_sprouts", new byk(ceg.c.a(cva.h, cvb.y).a().c().a(cae.M)));
   public static final buo mq = a("crimson_stem", a(cvb.ac));
   public static final buo mr = a("stripped_crimson_stem", a(cvb.ac));
   public static final buo ms = a("crimson_hyphae", new bzl(ceg.c.a(cva.z, cvb.ad).d(2.0F).a(cae.z)));
   public static final buo mt = a("stripped_crimson_hyphae", new bzl(ceg.c.a(cva.z, cvb.ad).d(2.0F).a(cae.z)));
   public static final buo mu = a("crimson_nylium", new byp(ceg.c.a(cva.I, cvb.ab).h().d(0.4F).a(cae.A).d()));
   public static final buo mv = a("crimson_fungus", new bwx(ceg.c.a(cva.e, cvb.K).c().a().a(cae.B), () -> kh.bC));
   public static final buo mw = a("shroomlight", new buo(ceg.c.a(cva.t, cvb.D).d(1.0F).a(cae.D).a(var0 -> 15)));
   public static final buo mx = a("weeping_vines", new cbq(ceg.c.a(cva.e, cvb.K).d().a().c().a(cae.E)));
   public static final buo my = a("weeping_vines_plant", new cbr(ceg.c.a(cva.e, cvb.K).a().c().a(cae.E)));
   public static final buo mz = a("twisting_vines", new cbg(ceg.c.a(cva.e, cvb.y).d().a().c().a(cae.E)));
   public static final buo mA = a("twisting_vines_plant", new cbh(ceg.c.a(cva.e, cvb.y).a().c().a(cae.E)));
   public static final buo mB = a("crimson_roots", new bzk(ceg.c.a(cva.h, cvb.K).a().c().a(cae.C)));
   public static final buo mC = a("crimson_planks", new buo(ceg.c.a(cva.z, cvb.ac).a(2.0F, 3.0F).a(cae.a)));
   public static final buo mD = a("warped_planks", new buo(ceg.c.a(cva.z, cvb.af).a(2.0F, 3.0F).a(cae.a)));
   public static final buo mE = a("crimson_slab", new bzw(ceg.c.a(cva.z, mC.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo mF = a("warped_slab", new bzw(ceg.c.a(cva.z, mD.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo mG = a("crimson_pressure_plate", new byy(byy.a.a, ceg.c.a(cva.z, mC.s()).a().d(0.5F).a(cae.a)));
   public static final buo mH = a("warped_pressure_plate", new byy(byy.a.a, ceg.c.a(cva.z, mD.s()).a().d(0.5F).a(cae.a)));
   public static final buo mI = a("crimson_fence", new bwq(ceg.c.a(cva.z, mC.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo mJ = a("warped_fence", new bwq(ceg.c.a(cva.z, mD.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo mK = a("crimson_trapdoor", new cbb(ceg.c.a(cva.z, mC.s()).d(3.0F).a(cae.a).b().a(bup::a)));
   public static final buo mL = a("warped_trapdoor", new cbb(ceg.c.a(cva.z, mD.s()).d(3.0F).a(cae.a).b().a(bup::a)));
   public static final buo mM = a("crimson_fence_gate", new bwr(ceg.c.a(cva.z, mC.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo mN = a("warped_fence_gate", new bwr(ceg.c.a(cva.z, mD.s()).a(2.0F, 3.0F).a(cae.a)));
   public static final buo mO = a("crimson_stairs", new cak(mC.n(), ceg.c.a((ceg)mC)));
   public static final buo mP = a("warped_stairs", new cak(mD.n(), ceg.c.a((ceg)mD)));
   public static final buo mQ = a("crimson_button", new cbx(ceg.c.a(cva.o).a().d(0.5F).a(cae.a)));
   public static final buo mR = a("warped_button", new cbx(ceg.c.a(cva.o).a().d(0.5F).a(cae.a)));
   public static final buo mS = a("crimson_door", new bwb(ceg.c.a(cva.z, mC.s()).d(3.0F).a(cae.a).b()));
   public static final buo mT = a("warped_door", new bwb(ceg.c.a(cva.z, mD.s()).d(3.0F).a(cae.a).b()));
   public static final buo mU = a("crimson_sign", new cal(ceg.c.a(cva.z, mC.s()).a().d(1.0F).a(cae.a), cfq.g));
   public static final buo mV = a("warped_sign", new cal(ceg.c.a(cva.z, mD.s()).a().d(1.0F).a(cae.a), cfq.h));
   public static final buo mW = a("crimson_wall_sign", new cbl(ceg.c.a(cva.z, mC.s()).a().d(1.0F).a(cae.a).a(mU), cfq.g));
   public static final buo mX = a("warped_wall_sign", new cbl(ceg.c.a(cva.z, mD.s()).a().d(1.0F).a(cae.a).a(mV), cfq.h));
   public static final buo mY = a("structure_block", new caq(ceg.c.a(cva.J, cvb.x).h().a(-1.0F, 3600000.0F).f()));
   public static final buo mZ = a("jigsaw", new bxr(ceg.c.a(cva.J, cvb.x).h().a(-1.0F, 3600000.0F).f()));
   public static final buo na = a("composter", new bvk(ceg.c.a(cva.y).d(0.6F).a(cae.a)));
   public static final buo nb = a("target", new cay(ceg.c.a(cva.t, cvb.p).d(0.5F).a(cae.c)));
   public static final buo nc = a("bee_nest", new buk(ceg.c.a(cva.y, cvb.t).d(0.3F).a(cae.a)));
   public static final buo nd = a("beehive", new buk(ceg.c.a(cva.y).d(0.6F).a(cae.a)));
   public static final buo ne = a("honey_block", new bxk(ceg.c.a(cva.r, cvb.q).b(0.4F).c(0.5F).b().a(cae.n)));
   public static final buo nf = a("honeycomb_block", new buo(ceg.c.a(cva.r, cvb.q).d(0.6F).a(cae.p)));
   public static final buo ng = a("netherite_block", new buo(ceg.c.a(cva.J, cvb.E).h().a(50.0F, 1200.0F).a(cae.P)));
   public static final buo nh = a("ancient_debris", new buo(ceg.c.a(cva.J, cvb.E).h().a(30.0F, 1200.0F).a(cae.Q)));
   public static final buo ni = a("crying_obsidian", new bvu(ceg.c.a(cva.I, cvb.E).h().a(50.0F, 1200.0F).a(var0 -> 10)));
   public static final buo nj = a("respawn_anchor", new bzj(ceg.c.a(cva.I, cvb.E).h().a(50.0F, 1200.0F).a(var0 -> bzj.a(var0, 15))));
   public static final buo nk = a("potted_crimson_fungus", new bwv(mv, ceg.c.a(cva.o).c().b()));
   public static final buo nl = a("potted_warped_fungus", new bwv(mm, ceg.c.a(cva.o).c().b()));
   public static final buo nm = a("potted_crimson_roots", new bwv(mB, ceg.c.a(cva.o).c().b()));
   public static final buo nn = a("potted_warped_roots", new bwv(mo, ceg.c.a(cva.o).c().b()));
   public static final buo no = a("lodestone", new buo(ceg.c.a(cva.L).h().d(3.5F).a(cae.R)));
   public static final buo np = a("blackstone", new buo(ceg.c.a(cva.I, cvb.E).h().a(1.5F, 6.0F)));
   public static final buo nq = a("blackstone_stairs", new cak(np.n(), ceg.c.a((ceg)np)));
   public static final buo nr = a("blackstone_wall", new cbk(ceg.c.a((ceg)np)));
   public static final buo ns = a("blackstone_slab", new bzw(ceg.c.a((ceg)np).a(2.0F, 6.0F)));
   public static final buo nt = a("polished_blackstone", new buo(ceg.c.a((ceg)np).a(2.0F, 6.0F)));
   public static final buo nu = a("polished_blackstone_bricks", new buo(ceg.c.a((ceg)nt).a(1.5F, 6.0F)));
   public static final buo nv = a("cracked_polished_blackstone_bricks", new buo(ceg.c.a((ceg)nu)));
   public static final buo nw = a("chiseled_polished_blackstone", new buo(ceg.c.a((ceg)nt).a(1.5F, 6.0F)));
   public static final buo nx = a("polished_blackstone_brick_slab", new bzw(ceg.c.a((ceg)nu).a(2.0F, 6.0F)));
   public static final buo ny = a("polished_blackstone_brick_stairs", new cak(nu.n(), ceg.c.a((ceg)nu)));
   public static final buo nz = a("polished_blackstone_brick_wall", new cbk(ceg.c.a((ceg)nu)));
   public static final buo nA = a("gilded_blackstone", new buo(ceg.c.a((ceg)np).a(cae.U)));
   public static final buo nB = a("polished_blackstone_stairs", new cak(nt.n(), ceg.c.a((ceg)nt)));
   public static final buo nC = a("polished_blackstone_slab", new bzw(ceg.c.a((ceg)nt)));
   public static final buo nD = a("polished_blackstone_pressure_plate", new byy(byy.a.b, ceg.c.a(cva.I, cvb.E).h().a().d(0.5F)));
   public static final buo nE = a("polished_blackstone_button", new cao(ceg.c.a(cva.o).a().d(0.5F)));
   public static final buo nF = a("polished_blackstone_wall", new cbk(ceg.c.a((ceg)nt)));
   public static final buo nG = a("chiseled_nether_bricks", new buo(ceg.c.a(cva.I, cvb.K).h().a(2.0F, 6.0F).a(cae.L)));
   public static final buo nH = a("cracked_nether_bricks", new buo(ceg.c.a(cva.I, cvb.K).h().a(2.0F, 6.0F).a(cae.L)));
   public static final buo nI = a("quartz_bricks", new buo(ceg.c.a((ceg)fz)));

   private static ToIntFunction<ceh> a(int var0) {
      return var1 -> var1.c(cex.r) ? _snowman : 0;
   }

   private static Boolean a(ceh var0, brc var1, fx var2, aqe<?> var3) {
      return false;
   }

   private static Boolean b(ceh var0, brc var1, fx var2, aqe<?> var3) {
      return true;
   }

   private static Boolean c(ceh var0, brc var1, fx var2, aqe<?> var3) {
      return _snowman == aqe.ac || _snowman == aqe.af;
   }

   private static buj a(bkx var0) {
      return new buj(_snowman, ceg.c.a(cva.C, var1 -> var1.c(buj.a) == cev.b ? _snowman.f() : cvb.e).a(cae.a).d(0.2F).b());
   }

   private static bzl a(cvb var0, cvb var1) {
      return new bzl(ceg.c.a(cva.y, var2 -> var2.c(bzl.e) == gc.a.b ? _snowman : _snowman).d(2.0F).a(cae.a));
   }

   private static buo a(cvb var0) {
      return new bzl(ceg.c.a(cva.z, var1 -> _snowman).d(2.0F).a(cae.z));
   }

   private static boolean a(ceh var0, brc var1, fx var2) {
      return true;
   }

   private static boolean b(ceh var0, brc var1, fx var2) {
      return false;
   }

   private static cai b(bkx var0) {
      return new cai(_snowman, ceg.c.a(cva.F, _snowman).d(0.3F).a(cae.g).b().a(bup::a).a(bup::b).b(bup::b).c(bup::b));
   }

   private static bxx b() {
      return new bxx(ceg.c.a(cva.E).d(0.2F).d().a(cae.c).b().a(bup::c).b(bup::b).c(bup::b));
   }

   private static bzs a(bkx var0, ceg.c var1) {
      ceg.e _snowman = (var0x, var1x, var2x) -> {
         ccj _snowmanx = var1x.c(var2x);
         if (!(_snowmanx instanceof cde)) {
            return true;
         } else {
            cde _snowmanx = (cde)_snowmanx;
            return _snowmanx.l();
         }
      };
      return new bzs(_snowman, _snowman.d(2.0F).e().b().b(_snowman).c(_snowman));
   }

   private static cea a(boolean var0) {
      ceg.e _snowman = (var0x, var1x, var2) -> !var0x.c(cea.b);
      return new cea(_snowman, ceg.c.a(cva.N).d(1.5F).a(bup::b).b(_snowman).c(_snowman));
   }

   private static buo a(String var0, buo var1) {
      return gm.a(gm.Q, _snowman, _snowman);
   }

   public static void a() {
      buo.m.forEach(ceg.a::a);
   }

   static {
      for (buo _snowman : gm.Q) {
         UnmodifiableIterator var2 = _snowman.m().a().iterator();

         while (var2.hasNext()) {
            ceh _snowmanx = (ceh)var2.next();
            buo.m.b(_snowmanx);
         }

         _snowman.r();
      }
   }
}
